### ISSUE TITLE
CFE Fish Data

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1024]
The CFE fish data spreadsheet (attached) hasn't been imported. @timlinux you mentioned there were issues with this. Please let me know what the issues are? @dimasciput 

[CFR Fish Data for FBIS.xlsx](https://github.com/kartoza/django-bims/files/2995232/CFR.Fish.Data.for.FBIS.xlsx)

**Comment by dimasciput** [comment]
Hi @toniolsen , the issue is the data is not following with our standard. For example the date : 
![image](https://user-images.githubusercontent.com/1979569/54805338-3b532700-4ca9-11e9-8b44-2e9d4b48ba33.png)

I will attached the template here, and please update your data to follow that format.

**Comment by dimasciput** [comment]
@toniolsen , Here is the template : 
[fish_template.zip](https://github.com/kartoza/django-bims/files/2995296/fish_template.zip)

**Comment by toniolsen** [comment]
Thanks @dimasciput. I will do this as soon as possible.

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux @helendallas @toniolsen - before Toni goes ahead - if we change the CFR fish data to fit this template then we will lose columns that are important  - like taxonomic hierarchy (kingdom, phylum, class...etc), conservation status, sampling method, effort and abundance? Even though the GBIF data don't have all these information columns, surely these columns still need to be retained? 

My understanding was that we need to convert the GBIF data to fit this 'master fish template' (detailed in ticket 916)? 

Please see that ticket 916 also explains that SAIAB data needs to be removed first because they are already in GBIF, to avoid duplication of those data. 

If this is not possible for V2, then maybe we need to consider sticking to the CFR fish data and then adding the GBIF data for V3 instead? @helendallas? @timlinux?

**Comment by toniolsen** [comment]
Here is the formatted CFE fish data. Let me know if there are any further issues.
@dimasciput @timlinux @jeremyshelton 

[CFR Fish Data for FBIS.xlsx](https://github.com/kartoza/django-bims/files/3028159/CFR.Fish.Data.for.FBIS.xlsx)

**Comment by dimasciput** [comment]
@toniolsen will try to process this, but data with unspecified date won't be added to the database since it's necessary information.

**Comment by toniolsen** [comment]
@dimasciput thank you! It is fine if the sites with unspecified dates are not added.

**Comment by dimasciput** [comment]
xls converted to csv : 
[CFRFishDistribution_catchments-Table 1.csv.zip](https://github.com/kartoza/django-bims/files/3047629/CFRFishDistribution_catchments-Table.1.csv.zip)
