### ISSUE TITLE
All filters should have tick boxes and not drop downs

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1032]
Please can all the filters from Conservation status down to Collector/Assessor have tick boxes and not drop downs. Just like you have it for the Reference Category filter. 
@timlinux @dimasciput @Christiaanvdm 

![Screen Shot 2019-03-22 at 9 14 58 AM](https://user-images.githubusercontent.com/43198125/54806627-3e3b2100-4c83-11e9-8bc6-7a44adb0ffab.png)

**Comment by dimasciput** [comment]
@toniolsen @timlinux the problem is the list is going to be very big, and it could take a lot of space and we can't easily search them. This issue is solved with the multiple select currently we have implemented. 

![bims-2](https://user-images.githubusercontent.com/1979569/54898256-1a374400-4efe-11e9-8ff9-e24c2433fb4e.gif)
