### ISSUE TITLE
Empty sass form

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1192]
![image](https://user-images.githubusercontent.com/178003/56360732-d1656900-61e5-11e9-8e18-0ea365dbfe01.png)

![image](https://user-images.githubusercontent.com/178003/56360746-d62a1d00-61e5-11e9-8c76-601c08151d89.png)

Can you check why this is coming up empty @dimasciput ?

**Comment by timlinux** [comment]
CC @helendallas

**Comment by helendallas** [comment]
@dimasciput @timlinux 
Not sure what you did for this ticket...data now missing, see screenshot. Please explain what the issue was, thanks
![Screenshot_2019-05-06 Django BIMS SASS Dashboard Single Site](https://user-images.githubusercontent.com/45286876/57214584-b323a980-6fea-11e9-9f8a-d86670c81f95.png)

**Comment by dimasciput** [comment]
@helendallas This is because in the form there is taxa but no abbundance data. You can check the db

**Comment by dimasciput** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1979569/57215677-d4e75580-7017-11e9-8274-543ec8c8367e.png">

@helendallas

**Comment by dimasciput** [comment]
no abbundance → no sass and aspt score
