### ISSUE TITLE
Flat pages

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1287]
@dimasciput @toniolsen @timlinux 

For About, Contact, Upload data, Validate records, Update records - please use FBIS font, charcoal colour and avoid cropping in on background image if possible. Please rather use font #18A090 throughout when colour is needed. 

<img width="1440" alt="Screenshot 2019-05-15 at 13 18 33" src="https://user-images.githubusercontent.com/44292029/57791560-52f4dc00-773d-11e9-96da-9ac6b14aacfc.png">

**Comment by dimasciput** [comment]
@jeremyshelton it's pretty difficult to not crop the image and still looks good, since it will need to supports various resolutions. If it's not cropped it will look like repeated image like this : 
![image](https://user-images.githubusercontent.com/1979569/58071332-7d73e880-7bc6-11e9-80ca-5129a4f30767.png)

**Comment by jeremyshelton** [comment]
@dimasciput ok. We do not want repeat. Do you perhaps need me to send you an image with different dimensions for these pages?

**Comment by helendallas** [comment]
http://freshwaterbiodiversity.org/admin/flatpages/flatpage/1/change/
