### ISSUE TITLE
Check validation dates imported correctly

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1382]
We did some spot checks of validation dates

<img width="374" alt="PastedGraphic-7" src="https://user-images.githubusercontent.com/178003/58807010-33035a80-860f-11e9-9eea-4870f962c079.png">

Can you double check that all dates imported correctly?

Helen's is not correct - it should have ended some time close to 2015.

Also on the SASS form autocomplete, please filter to only show names of people who at some point have had SASS accreditation (even if it is not current).

**Comment by helendallas** [comment]
I checked again and it is blank.

![Screenshot_2019-07-31 Change user Django site admin](https://user-images.githubusercontent.com/45286876/62214164-c99c8f80-b3a4-11e9-9783-f07368a75b94.png)

The imported dates need to be carried over to the SASS data form, so that a user can see what data was collected by a SASS accredited person...

**Comment by dimasciput** [comment]
fixed on testing : http://testing.healthyrivers.kartoza.com/admin/people/profile/478/change/?_changelist_filters=q%3Dhelen

![image](https://user-images.githubusercontent.com/1979569/66537690-91a38c80-eb4b-11e9-8ee9-2d5553bee7ae.png)
