### ISSUE TITLE
Origin filter change (again, sorry) 

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#1436]
We tested the Non-native filter and realised that category "extralimital" is problematic because it changes depending on where the site is in South Africa.

Therefore, we would like to collapse the non-native filter (so remove the alien and extralimital category). So we will just have "Non-native" and "Native (with it's endemism categories - as they are)":
![Screenshot 2019-06-27 at 12 40 59](https://user-images.githubusercontent.com/43198125/60260214-50a7a500-98d9-11e9-9427-6b746fea66e3.png)

We changed the master list accordingly (see attached) so that species are categorised as either "Non-native" or "Native". Can you please link this to the fish species in FBIS.

Sorry for the back and forth, but this only came apparent once we tested it. 

[SA Master fish species list_Final.xlsx](https://github.com/kartoza/django-bims/files/3334240/SA.Master.fish.species.list_Final.xlsx)

@dimasciput @timlinux @jeremyshelton

**Comment by toniolsen** [comment]
So the final Origin filter options looks like this:
![IMG_5164](https://user-images.githubusercontent.com/43198125/60261567-826e3b00-98dc-11e9-8f33-78734b756fe6.JPG)

**Comment by dimasciput** [comment]
@toniolsen there are only 5 records on the xls? Can I just change extralimital/alien in the existing data to non-native for now?

**Comment by jeremyshelton** [comment]
Hi @dimasciput 
There were only five records showing because those records were 'selected' in the origin dropdown. (you can get the full data set by doing origin > select all). 

Alternatively, here is another version of the sheet with 'all origin' selected...
[SA.Master.fish.species.list_Final_FBIS_v2.xlsx](https://github.com/kartoza/django-bims/files/3341753/SA.Master.fish.species.list_Final_FBIS_v2.xlsx)
