### ISSUE TITLE
Users - Housekeeping

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1497]
I need a list of Users that do not "Own" any Sites or Data. This will allow me to go and delete users that have come in from the Rivers Database.

**Comment by dimasciput** [comment]
@helendallas here's the list : 
[users_without_ownership.zip](https://github.com/kartoza/django-bims/files/3479775/users_without_ownership.zip)

**Comment by helendallas** [comment]
Thanks Dimas.  
@toniolsen . I have checked these. Please can you systematically delete all these users. Dimas has extracted those that have no data ownership. If for some reason it does not allow you delete them then make a note on the spreadsheet although this shouldnt be the case.

After that please can you fill in first and last names of all registered users.

**Comment by helendallas** [comment]
[RIvers Database Legacy Users for deleting 2019 08 08.xlsx](https://github.com/kartoza/django-bims/files/3480398/RIvers.Database.Legacy.Users.for.deleting.2019.08.08.xlsx)

**Comment by toniolsen** [comment]
@helendallas @dimasciput 

I have deleted all those accounts now and have filled in first and last names of the registered users.
Can I neaten up and change the usernames too? or will that cause an issue when the user tries to log in? 

Also note that there are more users in the system than on our signup sheet, because there are some admin accounts as well as some users have two accounts (i.e. Dean Impson) and I am not sure which one I should delete.
