### ISSUE TITLE
A fourth pie chart for single and multi site dashboards

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1614]
@dimasciput 
We need a fourth pie chart added to all single and multi site dashboards. This will apply to all modules (fish, inverts, algae...). The fourth pie chart is for 'Biotope'. The categories for biotopes are different for the different modules, but will correspond with categories in the master data sheets and data upload forms for each module. 

For **fish**, it's just the four biotopes:
Slow-Deep
Slow-Shallow
Fast-Deep
Fast-Shallow

For **invertebrates**, its the seven 'broad biotopes':
Stones in current
Stones out of current
Marginal vegetation
Aquatic Vegetation
Gravel/sand/mud
Mixed
Unspecified

For **algae**, we will add the biotopes soon...

<img width="1000" alt="Screenshot 2019-09-13 at 12 46 51" src="https://user-images.githubusercontent.com/44292029/64857728-ab71b280-d625-11e9-870d-21f291555661.png">

@ann26 @timlinux @toniolsen

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton 

For invertebrates, its should just be the seven 'broad biotopes':
Stones in current
Stones out of current
Marginal vegetation
Aquatic Vegetation
Gravel/sand/mud
Mixed
Unspecified

I suspect that the data showing is because the Biobase Invertebrate data still need to be checked for Biotopes.

![Screenshot_2019-11-14 FBIS Map(4)](https://user-images.githubusercontent.com/45286876/68866579-51f93300-06fd-11ea-8c8d-9c00227e5988.png)


@dimasciput 
What is the easiest way for me to check the biotopes associated with Biobase data. I can see the data in the Admin Biotopes, but cannot see which data are associated with Biobase data

![Screenshot_2019-11-14 Select biotope to change Django site admin](https://user-images.githubusercontent.com/45286876/68866415-0cd50100-06fd-11ea-82d6-ea2ab413524e.png)

**Comment by helendallas** [comment]
I am assuming that I can edit on the form below:
![Screenshot_2019-11-14 Change biotope Django site admin](https://user-images.githubusercontent.com/45286876/68867364-5f62ed00-06fe-11ea-9071-eede0dee2988.png)

@dimasciput 
Please make sure that the pie chart uses the Broad Biotope only, even if it still requires me to edit the Biobase Biotopes into Broad,  Specific and Substratum

**Comment by helendallas** [comment]
@dimasciput 
I have reassigned Biobase Biotopes to our new Broad Biotope, Specific Biotope and Substratum categories. 

Spreadsheet attached.  Ready to be corrected by you i the back-end, thanks

[Biotopes Table from Biobase - with New Broad Biotope_Specific_Subtsratum.xlsx](https://github.com/kartoza/django-bims/files/3863867/Biotopes.Table.from.Biobase.-.with.New.Broad.Biotope_Specific_Subtsratum.xlsx)

**Comment by dimasciput** [comment]
@helendallas thanks, should be quick fix

**Comment by dimasciput** [comment]
`python manage.py fix_legacy_biotope -f {biotope_file.csv}`
