### ISSUE TITLE
Unable to return to SASS detailed dashboard after editing site

### ISSUE THREAD

**Issue by Aneri16** [kartoza/django-bims#1658]
@dimasciput 
After editing a SASS site, I am unable to return to the SASS detailed dashboard to select another date for editing. When I click the cross to take me back, a window saying "You don't have any session" pops up. I then have to go back to maps and re-enter the site code in order to select another date for editing.

![SASS edit](https://user-images.githubusercontent.com/55532903/65854017-9f8f2b80-e35b-11e9-9a1d-39b01a22f1b9.jpg)
![SASS edit 2](https://user-images.githubusercontent.com/55532903/65854056-c4839e80-e35b-11e9-8f3d-1c7959c702ac.jpg)

**Comment by helendallas** [comment]
@dimasciput 

We are still really battling to edit SASS data on the live website. When we change the Owner, and submit, it firstly asks us twice if we want to submit, then kicks us out. here is the link. 

Please can you investigate soonest and fix on live site as it is quite difficult to edit data.  The linked ticket also does not make sense to us. fix back btn #1659

http://freshwaterbiodiversity.org/source-reference-form/?session=1baee2ec-ae60-4fde-9d63-79e532004f94&identifier=sass-form&next=/sass/update/11494/

**Comment by dimasciput** [comment]
@helendallas 

> When we change the Owner, and submit, it firstly asks us twice if we want to submit, then kicks us out. 

Yes, that's the procedure, click `Next` to go to the source reference form, then click `Submit`. 

> Please can you investigate soonest and fix on live site as it is quite difficult to edit data. The linked ticket also does not make sense to us. fix back btn #1659

This ticket is only applied to the testing, if we want to update the live server, there will be a lot of changes, because there will also abiotic data. I will need 3 days for the live server maintenance.

I suggest to do it with the new tab when you want to update the SASS record, right-click on the SASS link, then when you finish just close the tab. 

<img width="587" alt="image" src="https://user-images.githubusercontent.com/1979569/66306569-2cbe1b80-e92c-11e9-8fda-defb5eb78049.png">

**Comment by helendallas** [comment]
@dimasciput 
Thanks, that is a good workaround. I will let @Aneri16 know

**Comment by jeremyshelton** [comment]
OK so now the error message window has been fixed, but now (after editing a site, and clicking 'x') the user gets directed back to the map - however, the user should get directed back to the sass dashboard instead!
