### ISSUE TITLE
Is our SA river coverage layer the best?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1668]
@NyakudyaA we are having an issue that many of the rivers on which we have sites do not feature in our current river coverage layer. Is there perhaps a better/updated/more detailed SA river layer that we could use instead?

@timlinux @helendallas @dimasciput

**Comment by NyakudyaA** [comment]
Hi @jeremyshelton I think this should be a tossup between the NGI rivers and the water affairs river layers. The water affairs rivers are at a scale of 1:500K while the NGI rivers are at a scale of 1:50k.

**Comment by jeremyshelton** [comment]
OK thanks @NyakudyaA 

@MikeSilberbauer we are having an issue that many of the rivers on which we have sites do not feature in our current river coverage layer. Is there perhaps a better/updated/more detailed SA river layer that we could use instead?

 Any suggestions?

@helendallas

**Comment by MikeSilberbauer** [comment]
Hi Jeremy,

Could you please check the metadata of river shapefile you are using? If it is the coverage described here:
http://www.dwa.gov.za/iwqs/gis_data/river/rivs500k.aspx
…then I stopped editing it about five years ago because software changes here meant that my applications no longer worked.

In August 2017, Heidi van Deventer (CSIR), Rudolf de Munnik (Esri SA) and I discussed the possibility of getting the rivers into a newer ArcGIS format which would retain the network topology. The objectives defined by Heidi were:


1.       To import the data into a feature class with datum Geographic WGS84 (Esri to provide the steps and the NTV2 grid to learn how to do this for the dams and other datasets).

2.       To ensure that the hydrological direction of  flow of each segment is correct

3.       That there is connectivity between the river reaches (segments)

4.       That reachcode numbers are retained for river reaches within the line feature class. Reachcode is linked to a QC code and would be retained particularly when additions are made to the river network.

5.       Explore the possibility of having topological connectivity between the rivers, coastline and estuaries.

This process appeared to fizzle out for lack of funding.

The 1:50 000 river arcs are available from NGI (Surveys and Mapping in Mowbray) and there was an effort a while back to convert the spaghetti lines into a coherent network. I am not sure how far this went. The raw 1:50 000 files correspond to the blue lines on the topographical maps, e.g. the Black River and Salt River here:

[cid:image002.png@01D579DD.07623E70]

Another effort to consolidate drainage information was:
Weepener HL, van den Berg HM, Metz M and Hamandawana H (2011) The development of a hydrologically improved Digital Elevation Model and derived products for South Africa based on the SRTM DEM. Water Research Commission, Report no. K5/1908, Pretoria.
Contact: Harold Weepener, ARC - Institute for Soil, Climate and Water (Telephone: 012 3102500, Email: iscwinfo@arc.agric.za<mailto:iscwinfo@arc.agric.za>).

The original tidying up of the 1:500 000 rivers here at RQIS took about ten years with up to ten GIS people working on the data when they had time between other tasks. We estimated that, given the same software and staff, it would take us 100 years to process the 1:50 000 river arcs to the same level of structure and accuracy.
The report for the 1:500 000 rivers is at http://www.dwa.gov.za/iwqs/gis_data/river/River_Report_01.pdf.

If you plan to start adding rivers to the existing layer, please consider making the updated versions publicly available. It might be a bit advanced for crowdsource editing, but maybe retired-water-affairs-sourcing would work?

Regards,
Mike

Michael Silberbauer
SilberbauerM@dwa.gov.za<mailto:SilberbauerM@dwa.gov.za> * www.dwa.gov.za/IWQS<http://www.dwa.gov.za/IWQS>
Resource Quality Information Services Tel: + 27 12 808 9605 (if broken, try 082 908 2895)
Fax: + 27 12 808 2702 or +27 12 808 0338

**Comment by MikeSilberbauer** [comment]
P.S.: this reference may help in working out which rivers you have:
van Deventer, H., Smith-Adao, L., Mbona, N., Petersen, C., Skowno, A., Collins, N., Grenfell, M., Lötter, M., Ollis, D., Scherman, P., Sieben, E., Job, N., and Snaddon, K., 2018. South African Inventory of Inland Aquatic Ecosystems. CSIR and SANBI. http://opus.sanbi.org:80/handle/20.500.12143/5847

Michael Silberbauer
SilberbauerM@dwa.gov.za<mailto:SilberbauerM@dwa.gov.za> * www.dwa.gov.za/IWQS<http://www.dwa.gov.za/IWQS>
Resource Quality Information Services Tel: + 27 12 808 9605 (if broken, try 082 908 2895)
Fax: + 27 12 808 2702 or +27 12 808 0338

**Comment by jeremyshelton** [comment]
Thanks so much for this @MikeSilberbauer 
Very helpful and we really appreciate you taking the time. 
We will discuss this in detail and keep you in the loop with which route we decide to go. 
@dimasciput @timlinux @helendallas

**Comment by timlinux** [comment]
As discussed with @jeremyshelton today, we will stick with the current rivers layer until we conclusively find some better source.
