### ISSUE TITLE
Some spatial filters gone?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1823]
@dimasciput 
Was busy doing some testing and noticed that some spatial filters seem to have disappeared? Are you perhaps busy working on these?

<img width="362" alt="Screenshot 2019-11-29 at 17 46 19" src="https://user-images.githubusercontent.com/44292029/69879542-5eba8100-12d0-11ea-8ed0-e08e1e7dd230.png">

**Comment by dimasciput** [comment]
Hi @jeremyshelton , this is because the list are generated from the admin page now, previously the list are hardcoded, it means that I need to update the code if there are changes needed. Now we can just update them from the admin, we can also re-order them too. I let you know how to do that in the next meeting.

**Comment by dimasciput** [comment]
@jeremyshelton To answer your specific question about why the filters are disappeared, it's because I haven't added them all, it's busy work :D.

**Comment by jeremyshelton** [comment]
@dimasciput ok copy that - makes sense 👍
