### ISSUE TITLE
Repetition in Abiotic Data dropdown?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#1874]
Some of the abiotic parameters (e.g. Phenols) seem to be depilated in the dropdown (when adding abiotic data), with some units in caps and others in lower case? Is it possible that two different sets of options were added? I think there was only meant to be one...?

<img width="664" alt="Screenshot 2020-01-28 at 15 44 32" src="https://user-images.githubusercontent.com/44292029/73269476-8e5d0b00-41e5-11ea-8bab-798b4b9e45da.png">

@helendallas

**Comment by helendallas** [comment]
@dimasciput 
I think this is bacause of different names imported from Biobase and Rivers Database. How is the best way to update this Dimas?

Should I provide a list of Biobase Abiotic data names, with the corrected names in a new column.

**Comment by dimasciput** [comment]
@helendallas yes, I think that will be great, thanks.

**Comment by helendallas** [comment]
@dimasciput Okay, I will work on this later, and send

**Comment by helendallas** [comment]
@dimasciput 

[Master List of Abiotic Data Variables with FBIS Names and Validation Limits 2020_02_25.xlsx](https://github.com/kartoza/django-bims/files/4248856/Master.List.of.Abiotic.Data.Variables.with.FBIS.Names.and.Validation.Limits.2020_02_25.xlsx)

Okay, so I have created a spreadsheet of original Biobase and Rivers Database Name **(Biobase or Rivers Database_Description**), with the proposed **FBIS_ Name**; as well as an indication if the Abiotic Variable needs to be retained and served in the FBIS Abiotic Continuous variable form (**Retain variable in FBIS abiotic list**).

All those variables in red and with **No** for Retain - should remain as legacy data that is included in the csv files for a site, but not included in FBIS going forward, i.e. not included in the FBIS Abiotic Continuous variables list.

The list should include:
**Variable (unit)**

Alkalinity - total (mg ℓ-1)
Temperature (degrees C)
etc.

On the abiotic form - is it possible to rather provide all the FBIS Abiotic Continuous variables as you have done the fish species lists, rather than as a dropdown.  If this is a big job then please just make a separate ticket that gets flagged for later enhancement.

**Variable (unit) (listed alphabetically)      ;       Measured (as a tick box)       ;     Value (to be filled in)**
 

I have also included Validation Minimum and Maximum values for each variable. This feeds into the Setting of ranges for Abiotic parameters.

Please shout if anything is unclear.

**Comment by dimasciput** [comment]
@helendallas thanks for the list, I will try to incorporate it to the site.

> On the abiotic form - is it possible to rather provide all the FBIS Abiotic Continuous variables as you have done the fish species lists, rather than as a dropdown. If this is a big job then please just make a separate ticket that gets flagged for later enhancement.

Yes, please make a separate ticket for the to-do list.

**Comment by dimasciput** [comment]
Hi @helendallas , we can't use this format : 
![image](https://user-images.githubusercontent.com/1979569/75305417-99549b00-5878-11ea-94df-f1aefb7e719a.png)
It will have a problem when exporting the data to csv. Do you have an alternative?

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas 

Alternative format: mg/l

**Comment by helendallas** [comment]
@dimasciput correct mg/l; also mS/m -  essentially wherever there is a -1, it can become /
