### ISSUE TITLE
User clean up

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#1901]
Anyone from Rivers DB that is registered as a user but does not own any data can be deleted.
**Users that have registered on FBIS should not be deleted.**
All lower case names should merge into the upper case names.

![Screenshot 2020-02-21 at 09 37 26](https://user-images.githubusercontent.com/178003/75022356-d8a47580-548d-11ea-9977-cccb539a12c2.png)

CC @helendallas

**Comment by timlinux** [comment]
Note for FRC staff:

If users email have changed, just overwrite their user email in their old account rather than creating a new one.

![image](https://user-images.githubusercontent.com/178003/75022487-12757c00-548e-11ea-860e-6360ef1bfaf8.png)

**Comment by dimasciput** [comment]
```
{'dupe_count': 2, 'dupe_id': u'AnneliseGerber'}
{'dupe_count': 2, 'dupe_id': u'BentleyEngelbrecht'}
{'dupe_count': 2, 'dupe_id': u'BhekisisaCele'}
{'dupe_count': 2, 'dupe_id': u'BrandonWynne'}
{'dupe_count': 2, 'dupe_id': u'BrettAdie'}
{'dupe_count': 2, 'dupe_id': u'BrianFowles'}
{'dupe_count': 2, 'dupe_id': u'ByronBester'}
{'dupe_count': 2, 'dupe_id': u'ByronGrant'}
{'dupe_count': 3, 'dupe_id': u'CandiceHaskins'}
{'dupe_count': 2, 'dupe_id': u'CecileReed'}
{'dupe_count': 2, 'dupe_id': u'ChantelPetersen'}
{'dupe_count': 2, 'dupe_id': u'CharlesPemberton'}
{'dupe_count': 3, 'dupe_id': u'ChristaThirion'}
{'dupe_count': 3, 'dupe_id': u'ColleenTodd'}
{'dupe_count': 2, 'dupe_id': u'DaleKindler'}
{'dupe_count': 2, 'dupe_id': u'DeanImpson'}
{'dupe_count': 2, 'dupe_id': u'DeanOllis'}
{'dupe_count': 2, 'dupe_id': u'DionneCrafford'}
{'dupe_count': 2, 'dupe_id': u'Dirkvan Driel'}
{'dupe_count': 2, 'dupe_id': u'EarlHerdien'}
{'dupe_count': 2, 'dupe_id': u'ElliotWeni'}
{'dupe_count': 2, 'dupe_id': u'Ferdinandde Moor'}
{'dupe_count': 2, 'dupe_id': u'Ferdyde Moor'}
{'dupe_count': 2, 'dupe_id': u'FulufheloMafelatshuma'}
{'dupe_count': 2, 'dupe_id': u'GeordieRactliffe'}
{'dupe_count': 2, 'dupe_id': u'GerhardDiedericks'}
{'dupe_count': 2, 'dupe_id': u'GinaWalsh'}
{'dupe_count': 2, 'dupe_id': u'GraemeWilliams'}
{'dupe_count': 2, 'dupe_id': u'HanjoFourie'}
{'dupe_count': 2, 'dupe_id': u'HeatherMalan'}
{'dupe_count': 2, 'dupe_id': u'HelenDallas'}
{'dupe_count': 2, 'dupe_id': u'HelenJames'}
{'dupe_count': 2, 'dupe_id': u'HendrickSithole'}
{'dupe_count': 2, 'dupe_id': u'HermienRoux'}
{'dupe_count': 2, 'dupe_id': u'HugoRetief'}
{'dupe_count': 2, 'dupe_id': u'Humbulani EdwardMunzhelele'}
{'dupe_count': 2, 'dupe_id': u'IanBailey'}
{'dupe_count': 2, 'dupe_id': u'JeremyShelton'}
{'dupe_count': 2, 'dupe_id': u'JohanEngelbrecht'}
{'dupe_count': 2, 'dupe_id': u'JustineEwart-Smith'}
{'dupe_count': 2, 'dupe_id': u'KateMacEwan'}
{'dupe_count': 2, 'dupe_id': u'KateSnaddon'}
{'dupe_count': 2, 'dupe_id': u'KululwaMkosana'}
{'dupe_count': 2, 'dupe_id': u'KylieFarrell'}
{'dupe_count': 2, 'dupe_id': u'LizDay'}
{'dupe_count': 2, 'dupe_id': u'LornaNtshebe'}
{'dupe_count': 2, 'dupe_id': u'MandyUys'}
{'dupe_count': 2, 'dupe_id': u'MarieWatson'}
{'dupe_count': 2, 'dupe_id': u'Mariennede Villiers'}
{'dupe_count': 2, 'dupe_id': u'MarkGraham'}
{'dupe_count': 2, 'dupe_id': u'MathewRoss'}
{'dupe_count': 2, 'dupe_id': u'MbedziMulalo'}
{'dupe_count': 2, 'dupe_id': u'MelanieWithers'}
{'dupe_count': 2, 'dupe_id': u'MichielJonker'}
{'dupe_count': 2, 'dupe_id': u'MickAngliss'}
{'dupe_count': 2, 'dupe_id': u'MlondoloziMbikwana'}
{'dupe_count': 2, 'dupe_id': u'NelisiweMkhaliphi'}
{'dupe_count': 2, 'dupe_id': u'NicoRossouw'}
{'dupe_count': 2, 'dupe_id': u'NikiteMuller'}
{'dupe_count': 2, 'dupe_id': u'NjabuloNgema'}
{'dupe_count': 2, 'dupe_id': u'NkosinathiTshefu'}
{'dupe_count': 3, 'dupe_id': u'NobubeleBoniwe'}
{'dupe_count': 2, 'dupe_id': u'NosiphiwoKetse'}
{'dupe_count': 2, 'dupe_id': u'NqabisaGwentshe'}
{'dupe_count': 2, 'dupe_id': u'NtswakiDitlhale'}
{'dupe_count': 2, 'dupe_id': u'PatsyScherman'}
{'dupe_count': 2, 'dupe_id': u'PaulFouche'}
{'dupe_count': 2, 'dupe_id': u'PetroVos'}
{'dupe_count': 2, 'dupe_id': u'Phetole PeterRamollo'}
{'dupe_count': 2, 'dupe_id': u'PietMuller'}
{'dupe_count': 2, 'dupe_id': u'Pietervan Eeden'}
{'dupe_count': 2, 'dupe_id': u'PortraitTshatshu'}
{'dupe_count': 2, 'dupe_id': u'RafiekaJohaar'}
{'dupe_count': 2, 'dupe_id': u'RamogaleSekwele'}
{'dupe_count': 2, 'dupe_id': u'RobPalmer'}
{'dupe_count': 2, 'dupe_id': u'RobertSieberitz'}
{'dupe_count': 2, 'dupe_id': u'ShaddaiDaniel'}
{'dupe_count': 2, 'dupe_id': u'SiyandaMzileni'}
{'dupe_count': 2, 'dupe_id': u'TarynRossenrode'}
{'dupe_count': 2, 'dupe_id': u'ThembelaBushula'}
{'dupe_count': 2, 'dupe_id': u'TobileBokwe'}
{'dupe_count': 2, 'dupe_id': u'ToniBelcher'}
{'dupe_count': 2, 'dupe_id': u'TovhoNdiitwani'}
{'dupe_count': 2, 'dupe_id': u'TracyMeintjes'}
{'dupe_count': 2, 'dupe_id': u'WarrenAken'}
{'dupe_count': 2, 'dupe_id': u'WynandMalherbe'}
{'dupe_count': 2, 'dupe_id': u'Xolewa GloriaBhele'}
{'dupe_count': 2, 'dupe_id': u'ZaneleMabaso'}
{'dupe_count': 2, 'dupe_id': u'ZinziMboweni'}
```

**Comment by helendallas** [comment]
@timlinux I am keen to clean up this list but am not clear on what needs to happen.

Please can you provide me with a step by step process so that I can begin. Thanks

**Comment by dimasciput** [comment]
@helendallas the duplicated user has been merged, here are the list of affected users : 
[duplicated_users.zip](https://github.com/kartoza/django-bims/files/4367006/duplicated_users.zip)
But this is only for testing site, so please check there first.

**Comment by helendallas** [comment]
@dimasciput 
It is rather hard to check this list. 

One issue is all the Owners/Collectors that have been imported from the ingestion of data:
![Screenshot_2020-03-24 Select user to change Django site admin(1)](https://user-images.githubusercontent.com/45286876/77416827-11a57200-6dcd-11ea-9e28-58f2bbe64ad5.png)

We ideally need a way to differentiate between suers who actually sign up to FBIS, and those who have been made users due to data imported from Rivers DB, Biobase or other data scuh as fish inverts and algae.  Also a date of user signup would be useful

@timlinux @dimasciput 
Please give this some more thought...there really should be different categories or something to assist in the administration of the users.

![Screenshot_2020-03-24 Select user to change Django site admin(2)](https://user-images.githubusercontent.com/45286876/77417095-93959b00-6dcd-11ea-9ba0-1e244c88da73.png)


Also Can you add functionality that if I delete a user, and there is data associated with that user that I get an alert.  Like a cascade update warning in MS Access.

Sorry to be going on about this, but as it is 15 pages of users is a nightmare to maintain. Please revert soonest

**Comment by dimasciput** [comment]
@helendallas user that actually sign up has email on their profile. And yes if you delete a user who is an owner of a record, it will show you a message.

**Comment by helendallas** [comment]
@dimasciput Okay, so if I sort on email I can get signed up suers only. I have randomly checked duplicate list, seems okay.  Some are not being picked up because name is similar but email is different:

![Screenshot_2020-03-25 Select user to change Django site admin](https://user-images.githubusercontent.com/45286876/77506876-a1036180-6e6f-11ea-8431-a6d647571ee8.png)

Your system does not pick up the same use, where emails are different, and also if data has been ingested in a name that has initials for e.g. but which is the same as a user.

![Screenshot_2020-03-25 Select user to change Django site admin(1)](https://user-images.githubusercontent.com/45286876/77507189-93021080-6e70-11ea-80fd-247dfc3c9dab.png)

Maybe you need a two step process, first check for duplicate users based on same email, then duplicate names that are similar.....

@timlinux ?

**Comment by helendallas** [comment]
@dimasciput Also we have updated a lot of the Collector/Owner names to First Name and Surname when we know the first name rather that initial in the data for ingestion. 

If a user exists in FBIS, will the record be assigned to the existing user? If not, then we will always be creating duplicates.

**Comment by dimasciput** [comment]
It will overwrite existing user with the same firstname and lastname.

**Comment by helendallas** [comment]
@dimasciput Okay hats good, so hoefully once we have cleaned up Collector/Owner names as best we can in the data then it will be less numerous

**Comment by timlinux** [comment]
Discussion on 26 March 2020 - Helen asked to deploy user management to live - she will then use the new tools to systematically work through the users list.

**Comment by helendallas** [comment]
@dimasciput Please let me know as soon as this has been deployed to the live site so that I can begin the user cleanup.

**Comment by helendallas** [comment]
@dimasciput I am adding this to FBIS V4 as it still has to be done and I really dont want it dropping off the radar

**Comment by dimasciput** [comment]
@helendallas updated in live site

**Comment by helendallas** [comment]
This will take some time for me to do. I am moving it to FBIS V5

**Comment by helendallas** [comment]
Closing this via #2201
