### ISSUE TITLE
Algal Data - Ready for ingestion

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1945]
@dimasciput I hope that the data is now correct and ready for ingestion.  I have reordered and renamed column and column headers to match others, and deleted the extra row and all unnecessary columns.

There are some columns that are unique to algae, including:

- **Curation process**: Frozen; Acid cleaned; Preserved lugols
- **Biomass Indicator: Chl A**: Artificial Substrate; Whole cobble
- **Chlorophyll a: benthic** : this is a value
- **Biomass Indicator: Ash Free Dry Mass** : Whole cobble
- **Ash Free Dry Mass** : this is a value
- **Autotrophic Index (AI)** : this is a value

I am not sure if some/all of these should be added to the abiotic list? If yes, then @Aneri16 knows how to add them to the Abiotic admin section.

- Sampling method: scrubbing
- Abundance measure: Density (cells/m2); Species valve/frustule count

- For Broad biotope - **artificial substrate** is new
- For Substratum - **artificial** is new

Also new:
- Analyst
- Analyses Institute

All sites in this study:

Snaddon   K, Ractliffe G, Ewart-Smith JL | 2014 | TMGA Ecological and   Hydropgeological Monitoring: Data Analysis Report

are also included in invertebrate data - not sure if the algal data can be hooked onto the same sites.

The data file is:
Algal Data For FBISV3_03 Mar 2020.xlsx

Link: https://www.dropbox.com/s/bopfjpok9bnpnh0/Algal%20Data%20For%20FBISV3_03%20Mar%202020.xlsx?dl=0

@jeremyshelton @philipfrenzel

**Comment by helendallas** [comment]
File is now this one:

**Comment by helendallas** [comment]
@philipfrenzel @jeremyshelton 
When the final algal data file is ready for ingestion, please add file name and dropbox link for final ingestion to this ticket, so that we can keep track of all data ingested systematically.

**Comment by philipfrenzel** [comment]
Both final algal spreadsheets (data and master list) have been uploaded to the shared FRC/Kartoza Dropbox folder. Links to the CSV files are as follows:
* Data: https://www.dropbox.com/s/eu6f96kr8wewfzk/SA%20Algal%20Data%20For%20FBISV3_26%20Mar%202020.csv?dl=0
* Master list: https://www.dropbox.com/s/0tvglzpdwbls8kc/SA%20Algal%20Master%20list%20FBISv3_27%20Mar%202020.csv?dl=0

In terms of the dropdown options for the master list, @dimasciput , please use the following:
**Divisions:** 
1. Bacillariophyta; 
2. Chlorophyta; 
3. Chrysophyta; 
4. Cryptophyta; 
5. Cyanophyta; 
6. Dinophyta; 
7. Euglenophyta; 
8. Rhodophyta; 
9. Xanthophyta;
10. Raphidophyta
11. Eustigmatophyta
12 Phaeophyta
13. Prasinophyta
14. Glaucophyta
15. Haptophyta

**Growth forms:** 
1. Colonial; 
2. Filamentous; 
3. Gelatinous masses; 
4. Single cells; 
5. Single cells/colonial; 
6. Single cells/filamentous; 
7. Unknown.

Side notes/comments: 
* @dimasciput , you will see that in the master list I added a column for the GBIF URL to the correct taxa. For some taxa, there are several records in GBIF and therefore needed to specify the most appropriate taxon. Please use these links. These links often differed to the links that you extracted from GBIF originally. Just thought I'd mention this. 
* Divisions 1 to 9 appear in the current master list, whereas 10 to 15 are other freshwater algal divisions that we need to cater for if future records are added. Some divisions, such as Prasinophyta and Haptophyta, contain primarily marine species, but they do have some freshwater species which is why I included them as one of the dropdown options.
* @helendallas and @jeremyshelton : Should we add a small description after each of the divisions e.g. Cyanophyta: Blue-green algae or Rhodophyta: Red algae? Or will the above list suffice for now?

Please let me know if there are any questions or need further explanations. I am planning to do some more functionality testing of the algae components on Monday.

@helendallas  @jeremyshelton  @dimasciput

**Comment by dimasciput** [comment]
@philipfrenzel @helendallas 
![image](https://user-images.githubusercontent.com/1979569/78316788-b7559f80-758a-11ea-880f-4c2621a8e5ae.png)

Please add a link to document or url for the published report, I can't create a published report reference without it.

**Comment by dimasciput** [comment]
@philipfrenzel 

> In terms of the dropdown options for the master list, @dimasciput , please use the following:
> Divisions:
> 
> Bacillariophyta;
> Chlorophyta;
> Chrysophyta;
> Cryptophyta;
> Cyanophyta;
> Dinophyta;
> Euglenophyta;
> Rhodophyta;
> Xanthophyta;
> Raphidophyta
> Eustigmatophyta
> 12 Phaeophyta
> Prasinophyta
> Glaucophyta
> Haptophyta

I'm unsure what is this for?

**Comment by philipfrenzel** [comment]
> @philipfrenzel @helendallas
> ![image](https://user-images.githubusercontent.com/1979569/78316788-b7559f80-758a-11ea-880f-4c2621a8e5ae.png)
> 
> Please add a link to document or url for the published report, I can't create a published report reference without it.

Hi @dimasciput 

I see that there are three published reports which have algal data assigned to them. Two of them I would like to confirm whether we have permission to serve up the actual reports. Regarding the TMGA report, @helendallas , I recall that we (FRC) need to get a signed letter of approval from the City to publish this report on FBIS. Do we have that yet, or are we going to publish it in the meantime?

@helendallas  If we are not allowed to serve up a published report itself, do we then classify the reference category as "unpublished data" even though an official report has been written?

@dimasciput  I will follow up regarding the other two published reports in the meantime. If the report itself is classified, then we may need to change the reference category of these reports. But I will be in touch.

**Comment by philipfrenzel** [comment]
> @philipfrenzel
> 
> > In terms of the dropdown options for the master list, @dimasciput , please use the following:
> > Divisions:
> > Bacillariophyta;
> > Chlorophyta;
> > Chrysophyta;
> > Cryptophyta;
> > Cyanophyta;
> > Dinophyta;
> > Euglenophyta;
> > Rhodophyta;
> > Xanthophyta;
> > Raphidophyta
> > Eustigmatophyta
> > 12 Phaeophyta
> > Prasinophyta
> > Glaucophyta
> > Haptophyta
> 
> I'm unsure what is this for?

@dimasciput 

These 15 dropdown options for division are for the algal master list. If someone adds a new taxon, they need to be able to assign a division from one of these 15 options. Currently, only the first 9 divisions are present in the current master list but we need to create options for the other divisions should users add these taxa in the future.

**Comment by philipfrenzel** [comment]
> > @philipfrenzel @helendallas
> > ![image](https://user-images.githubusercontent.com/1979569/78316788-b7559f80-758a-11ea-880f-4c2621a8e5ae.png)
> > Please add a link to document or url for the published report, I can't create a published report reference without it.
> 
> Hi @dimasciput
> 
> I see that there are three published reports which have algal data assigned to them. Two of them I would like to confirm whether we have permission to serve up the actual reports. Regarding the TMGA report, @helendallas , I recall that we (FRC) need to get a signed letter of approval from the City to publish this report on FBIS. Do we have that yet, or are we going to publish it in the meantime?
> 
> @helendallas If we are not allowed to serve up a published report itself, do we then classify the reference category as "unpublished data" even though an official report has been written?
> 
> @dimasciput I will follow up regarding the other two published reports in the meantime. If the report itself is classified, then we may need to change the reference category of these reports. But I will be in touch.

@dimasciput  I have received permission to upload the two published reports and have uploaded them via the document uploader into FBIS. I have also updated the .xlsx and .csv files in the Dropbox folder (they still have the old date i.e. 26 March 2020 in their title). Once I have found out what to do regarding the TMGA report from @helendallas , I will update the files accordingly.

**Comment by dimasciput** [comment]
> These 15 dropdown options for division are for the algal master list. If someone adds a new taxon, they need to be able to assign a division from one of these 15 options. Currently, only the first 9 divisions are present in the current master list but we need to create options for the other divisions should users add these taxa in the future.

@philipfrenzel can you please add these data to master list then?

**Comment by philipfrenzel** [comment]
@dimasciput  Done. I've added the dropdown options for you for taxon rank, division, growth form, origin, endemism and conservation status. The file name is still the same (i.e. 26 Mar for the data file and 27 Mar for the master list). I've converted it to a .csv file too.

**Comment by helendallas** [comment]
@philipfrenzel 
Letter re TMG sent. Awaiting approval. It may take a while though.

@dimasciput Can we not classify the report as Published Report, and then have the option to say, pdf not available. This is the same issue as with some of the Biobase reports. So the study reference is there, but the pdf is not.

**Comment by Aneri16** [comment]
@philipfrenzel @helendallas 
What we did for fish data where there was no PDF available for a report, @dimasciput suggested we put a link to a related site instead ie For a WWF Report by Roger Bills that was not available as PDF, we put a link to his page on the SAIAB website so that a user can contact him if they need to get hold of the report. The link would be in the Document Upload Link column, even though it obviously isn't a PDF. Would this help as an interim solution until you get permission from TMG?

**Comment by helendallas** [comment]
@Aneri16 Thanks but it doesnt help for historical reports that are nowhere on the internet

**Comment by helendallas** [comment]
Assuming algal data is ingested correctly. @philipfrenzel please can you have a quick random check on the testing and confirm please

**Comment by philipfrenzel** [comment]
@helendallas  I have checked a few sites where I know there are algal data and it seems as though some of the algal data are missing. 

For instance, site H6BERG-00002 (site code: T6_2a): If you download the CSV for this site, only 61 records appear even though there are 292 records in the raw data file. Interestingly, the overview dashboard displays the correct number of records (i.e. 292 for this site) but not all of these data are downloaded in the CSV. 

The same problem arises for site H6DUTO-00056 (site code: T8_2a). The CSV contains 124 records whilst the dashboard and the master list contain 281 records for this site.

Not why this is so? @dimasciput

**Comment by dimasciput** [comment]
@philipfrenzel ok let me check

**Comment by helendallas** [comment]
I have checked these same site for records, and all data seem to be visible in dashboard and csv files. I am closing ticket.
