### ISSUE TITLE
Add Unknown to Origin, endemism

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1996]
Please add "Unknown"option for Origin, Endemism and Conservation Status. (It may already be there for some)

This is needed as we ingest invertebrate and algal data since many of these taxa do not have this information.  It is better than leaving blank.

@philipfrenzel @jeremyshelton Please check that Unknown is added for the appropriate taxa and columns in the ingestion files.

**Comment by philipfrenzel** [comment]
No problem @helendallas . This was on my to-do list for Monday for the algae species master list based on the zoom call earlier this week. But I'll get onto this soon due to the urgency.

On a side note: I haven't unfortunately heard anything back from Pashni regarding the endemism of certain diatoms. So, unfortunately, most algae species will be classified as "unknown" for now.

@jeremyshelton

**Comment by philipfrenzel** [comment]
@helendallas @jeremyshelton . I've completed this for the algal list. 

Unfortunately the origin, endemism and conservation status isn't readily available for algae - hence I have populated the gaps with 'unknown'. When I hear back from Pashni re the endemism, I'll let you know. It'll be a small handful of taxa where this is known in SA, but would be nice to add. Hopefully we can add these data at a later stage.

**Comment by helendallas** [comment]
@jeremyshelton At the moment on the testing site, instead of unknown we have:

Unspecified for Origin and Endemism and Data Deficient for Conservation Status. 
Do you think we can retain as is ? or do these need to be changed to Unknown as per this ticket. The meaning is a bit different.

![Screenshot_2020-04-15 FBIS Map(8)](https://user-images.githubusercontent.com/45286876/79339881-d6a8e100-7f29-11ea-9b69-6c14e38d2350.png)

**Comment by jeremyshelton** [comment]
@helendallas for conservation status, remember there is a distinction between DD and NE. I suspect in most cases the correct category for invest and algae is NE, rather than DD? 
![Screenshot 2020-04-15 at 17 16 27](https://user-images.githubusercontent.com/44292029/79354604-e847b400-7f3c-11ea-8244-d985b7824d34.png)

For Origin and Endemism situations where we 'don't know' then to me Unknown may be more correct, but unspecified probably OK?

**Comment by helendallas** [comment]
@jeremyshelton @dimasciput 

Thanks Jeremy. Ok so for Conservation status anything in our master list that is unknown should be changed to Not evaluated.

@dimasciput Please then add Unknown as per this ticket for Origin and Endemism please.
@philipfrenzel Please note change for Conservation status

**Comment by philipfrenzel** [comment]
Thanks for the clarification. Done for algal data @helendallas @dimasciput

**Comment by helendallas** [comment]
@dimasciput 
Please remember to add:

Unknown for Origin
Unknown for Endemism

Also include in overview panel for species - it is there for endemism but not origin
![Screenshot_2020-04-17 FBIS Map(2)](https://user-images.githubusercontent.com/45286876/79564856-b9058400-80af-11ea-984c-8969b3f8e302.png)

**Comment by helendallas** [comment]
@dimasciput The master taxon files for algae, invertebrates and fish include these fields for all taxa in the list. These need to be brought into the FBI. At the moment they are not coming through correctly so please check.

**Comment by helendallas** [comment]
So it needs to be:
Origin: Unknown
Endemism: Unknown
Conservation Status: Not evaluated

Data on the testing site still have unspecifed and some blanks.
![image](https://user-images.githubusercontent.com/45286876/80221766-0a7cb880-8646-11ea-95ab-0c9f028b28b8.png)
