### ISSUE TITLE
1835 fish data records with no reference category 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2161]
@dimasciput @timlinux  here are 1835 fish data records with no reference category in fish data fbis csv download. However, all cells are populated for this field in the fish data sheet?
I can email you the csv if needed?
@helendallas @Aneri16

**Comment by helendallas** [comment]
@jeremyshelton has this been resolved?

**Comment by dimasciput** [comment]
@jeremyshelton there are only 10 fish without source references, it's because they are not given a title.

Here are the fish data : 

UUID | Original River Name | Original Site Code | FBIS Site Code | Site description | Refined Geomorphological Zone | Latitude | Longitude | Sampling Date | Kingdom | Phylum | Class | Order | Family | Genus | Species | Taxon | Taxon rank | Present | Sampling method | Sampling effort measure | Sampling effort value | Abundance measure | Abundance value | Broad biotope | Specific biotope | Substratum | Depth | Near Bed Velocity | COND | PH | DOPER | DO | TEMP | TURB | Collector/Owner | Collector/Owner Institute | Author(s) | Year | Source | Title | Reference category | URL | DOI | Document Upload Link | Notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ba503fbb-177c-446d-8f06-fc0fa9bbcf9d | Liesbeek | L1 |   | Approximately 20m above river crossing. Enter Kirstenbosch Gardens at top entrance and follow Stinkwood trail for 10 minutes |   | -33.98545 | 18.43032 | 1/1/2018 | Animalia | Chordata | Actinopterygii | Osmeriformes | Galaxiidae | Galaxias | zebratus | Galaxias zebratus | Species | 1 | Hand net | Time (min) | 60 | Number | 30 | Slow-Deep | Unspecified | Boulder | 0.8 |   | 0.8 | 6.15 |   | 86.5 | 18.1 |   | Toni Olsen & Lily Bovim | University of Cape Town & Freshwater Research Centre | Olsen T | 2018 |   |   | Thesis | http://hdl.handle.net/11427/29349 |   |   | Sites were sampled twice. The first sample period being Nov/Dec 2017 and the second Jan/Feb 2018.
e3afc9e0-3c0b-49db-ab3a-22dc8c6bba2d | Liesbeek | L2 |   | About 5m downstream from where the wall ends. |   | -33.98248 | 18.45135 | 1/1/2018 | Animalia | Chordata | Actinopterygii | Osmeriformes | Galaxiidae | Galaxias | zebratus | Galaxias zebratus | Species | 1 | Hand net | Time (min) | 60 | Number | 30 | Slow-Shallow | Unspecified | Cobble | 0.5 |   | 1.9 | 6.46 |   | 103.2 | 16.6 |   | Toni Olsen & Lily Bovim | University of Cape Town & Freshwater Research Centre | Olsen T | 2018 |   |   | Thesis | http://hdl.handle.net/11427/29349 |   |   | Sites were sampled twice. The first sample period being Nov/Dec 2017 and the second Jan/Feb 2018.
cec4f5a4-9836-4c7e-a599-0db3b7899f19 | Liesbeek | L3 |   | Canalised section, about 200m upstream from Gordons Gym. Directly opposite Starke Ayres. |   | -33.95236 | 18.47633 | 1/1/2018 | Animalia | Chordata | Actinopterygii | Osmeriformes | Galaxiidae | Galaxias | zebratus | Galaxias zebratus | Species | 1 | Hand net | Time (min) | 60 | Number | 30 | Slow-Shallow | Unspecified | Unspecified | 0.3 |   | 2.2 | 6.28 |   | 101.8 | 17.9 |   | Toni Olsen & Lily Bovim | University of Cape Town & Freshwater Research Centre | Olsen T | 2018 |   |   | Thesis | http://hdl.handle.net/11427/29349 |   |   | Sites were sampled twice. The first sample period being Nov/Dec 2017 and the second Jan/Feb 2018.
83824d8c-4ea2-4954-803e-54dc5e5e4988 | Diep | DP1 |   | About 2m downstream from the river crossing, in a big pool. |   | -34.00024 | 18.43577 | 1/1/2018 | Animalia | Chordata | Actinopterygii | Osmeriformes | Galaxiidae | Galaxias | zebratus | Galaxias zebratus | Species | 1 | Hand net | Time (min) | 60 | Number | 30 | Slow-Shallow | Unspecified | Cobble | 0.3 |   | 1.6 | 6.48 |   | 100.7 | 17.1 |   | Toni Olsen & Lily Bovim | University of Cape Town & Freshwater Research Centre | Olsen T | 2018 |   |   | Thesis | http://hdl.handle.net/11427/29349 |   |   | Sites were sampled twice. The first sample period being Nov/Dec 2017 and the second Jan/Feb 2018.
82312af8-cc4a-4016-a362-5353a375018e | Schusters | SCH1 |   | Directly below the bridge on the the way the picnic site. |   | -34.202488 | 18.374546 | 1/1/2018 | Animalia | Chordata | Actinopterygii | Osmeriformes | Galaxiidae | Galaxias | zebratus | Galaxias zebratus | Species | 1 | Hand net | Time (min) | 60 | Number | 27 | Slow-Shallow | Unspecified | Silt/Mud/Clay | 0.8 |   | 6.4 | 5.6 |   | 60.1 | 19.2 |   | Toni Olsen & Lily Bovim | University of Cape Town & Freshwater Research Centre | Olsen T | 2018 |   |   | Thesis | http://hdl.handle.net/11427/29349 |   |   | Sites were sampled twice. The first sample period being Nov/Dec 2017 and the second Jan/Feb 2018.
4e4a96a3-3421-4713-987b-af7bb6bfd020 | Silvermine | S1 |   | Directly below the bridge crossing in a big, vegetated pool |   | -34.0877 | 18.4187 | 1/1/2018 | Animalia | Chordata | Actinopterygii | Osmeriformes | Galaxiidae | Galaxias | zebratus | Galaxias zebratus | Species | 1 | Hand net | Time (min) | 60 | Number | 30 | Slow-Deep | Unspecified | Bedrock | 0.5 |   | 1.7 | 4.64 |   | 83.7 | 14.1 |   | Toni Olsen & Lily Bovim | University of Cape Town & Freshwater Research Centre | Olsen T | 2018 |   |   | Thesis | http://hdl.handle.net/11427/29349 |   |   | Sites were sampled twice. The first sample period being Nov/Dec 2017 and the second Jan/Feb 2018.
23b2ea7c-1907-4a39-8f9e-14a6105458db | Silvermine | S2 |   | About 2km along the path from the Sunbird centre. In the pool near the entrance point to the river. |   | -34.107582 | 18.409393 | 1/1/2018 | Animalia | Chordata | Actinopterygii | Osmeriformes | Galaxiidae | Galaxias | zebratus | Galaxias zebratus | Species | 1 | Hand net | Time (min) | 60 | Number | 30 | Fast-Deep | Unspecified | Bedrock | 0.3 |   | 2.5 | 4.69 |   | 60.5 | 16 |   | Toni Olsen & Lily Bovim | University of Cape Town & Freshwater Research Centre | Olsen T | 2018 |   |   | Thesis | http://hdl.handle.net/11427/29349 |   |   | Sites were sampled twice. The first sample period being Nov/Dec 2017 and the second Jan/Feb 2018.
25e286d1-dbeb-4b22-8040-5c3783191fae | Silvermine | S3 |   | Below the bridge crossing, in the pool below the gabion. |   | -34.130759 | 18.435185 | 1/1/2018 | Animalia | Chordata | Actinopterygii | Osmeriformes | Galaxiidae | Galaxias | zebratus | Galaxias zebratus | Species | 1 | Hand net | Time (min) | 60 | Number | 28 | Slow-Deep | Unspecified | Silt/Mud/Clay | 2 |   | 8.5 | 6.65 |   | 39.4 | 17.5 |   | Toni Olsen & Lily Bovim | University of Cape Town & Freshwater Research Centre | Olsen T | 2018 |   |   | Thesis | http://hdl.handle.net/11427/29349 |   |   | Sites were sampled twice. The first sample period being Nov/Dec 2017 and the second Jan/Feb 2018.
2230e3d4-c5f2-4f0f-a871-a64fe4b6eedf | Klawersvlei | AD1 |   | About 100m in a few pools below the waterfall. |   | -34.191667 | 18.419917 | 1/1/2018 | Animalia | Chordata | Actinopterygii | Osmeriformes | Galaxiidae | Galaxias | zebratus | Galaxias zebratus | Species | 1 | Hand net | Time (min) | 60 | Number | 30 | Slow-Deep | Unspecified | Cobble | 0.5 |   | 4.3 | 6.22 |   | 82.8 | 16.2 |   | Toni Olsen & Lily Bovim | University of Cape Town & Freshwater Research Centre | Olsen T | 2018 |   |   | Thesis | http://hdl.handle.net/11427/29349 |   |   | Sites were sampled twice. The first sample period being Nov/Dec 2017 and the second Jan/Feb 2018.
0ec20ae7-f3a4-4351-87c9-00a992d15969 | Disa | D1 |   | In Orangekoof nature reserve, directly below the bridge. |   | -34.008867 | 18.390767 | 1/1/2018 | Animalia | Chordata | Actinopterygii | Osmeriformes | Galaxiidae | Galaxias | zebratus | Galaxias zebratus | Species | 1 | Hand net | Time (min) | 60 | Number | 30 | Slow-Shallow | Unspecified | Cobble | 0.5 |   | 1.4 | 5.33 |   | 123.2 | 18 |   | Toni Olsen & Lily Bovim | University of Cape Town & Freshwater Research Centre | Olsen T | 2018 |   |   | Thesis | http://hdl.handle.net/11427/29349 |   |   | Sites were sampled twice. The first sample period being Nov/Dec 2017 and the second Jan/Feb 2018.

**Comment by jeremyshelton** [comment]
@dimasciput 
OK. I get 440 records with no reference source & info in full fish csv data download (see yellow highlights in attached). Do you think these are user-entered fish data? 

[FBIS fish data download 14 Sep 2020.xlsx](https://github.com/kartoza/django-bims/files/5216885/FBIS.fish.data.download.14.Sep.2020.xlsx)

@Aneri16 could you please check what the reference source for the above 10 records should be be?

**Comment by dimasciput** [comment]
@jeremyshelton I checked from database, only 10 without source references that coming from your csv. So this must be user entered data.

**Comment by Aneri16** [comment]
@dimasciput @jeremyshelton yeah I don't recognize those names from our fish data so must be user entered. 
The correct title for the thesis should be:
Tolerating climate change: a study on the influence of thermal history on thermal tolerance of Galaxias zebratus in rivers of the Cape Peninsula, South Africa

**Comment by jeremyshelton** [comment]
Thanks @Aneri16 and @dimasciput 

@helendallas should we think about a reference source label for user-entered survey data - maybe 'unpublished survey data', or just leave it blank?

**Comment by helendallas** [comment]
I would think the reference category should be **Unpublished data**, the dont need a reference source label.

Also is there a way to ensure the Collector/Owener is the persons fullname : Firstname and Surname

**Comment by jeremyshelton** [comment]
@dimasciput how easy is it to assign the reference category to 'Unpublished data' for these 440 records?

**Comment by dimasciput** [comment]
@jeremyshelton I have updated them to 'Unpublished data'

**Comment by jeremyshelton** [comment]
Thanks @dimasciput - I have checked it and it looks good 👍
