### ISSUE TITLE
We need to have correct the GeoContext items used for Site codes

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#2324]
So to generate the site codes according to this scheme:

![image](https://user-images.githubusercontent.com/178003/96101967-e780e200-0ecd-11eb-8121-ad155292fe40.png)

We need to have the relevant field present in the dataset

![image](https://user-images.githubusercontent.com/178003/96101913-db952000-0ecd-11eb-8c8c-465fcc4311f3.png)

And the mapping in geocontext service definitions should point to the correct field (not fid):

![image](https://user-images.githubusercontent.com/178003/96102023-f23b7700-0ecd-11eb-92fe-e0da38253cfe.png)

@mumaurice can you help to make sure these are all set up correctly so that we can generate site codes?

**Comment by mumaurice** [comment]
Hi @timlinux ,

Thank you for the ticket and the inquiry. If I understand correctly, the sites should have these attributes? If this is correct, it means that the data team (headed by Mapendo), can supply us with the data and we add related attributes? (Province, District, Catchment - level 1, and the fid corresponding to the sequence of the data collection per site?). Sorry, I got a bit confused because the screenshot presented here is for the catchment layer!

**Comment by helendallas** [comment]
See ticket #2287
