### ISSUE TITLE
Add a 'Find GBIF' button?

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2594]
Sorry @dimasciput @timlinux - looks like the details of this ticket somehow disappeared :(
Anyway, I wanted to ask whether there might be value in adding a 'Find GBIF' button in taxon management, just like the one for 'Find IUCN' - something that would allow us to easily pull GBIF data when a taxon is changed or a new taxon added?

...or does the interoperability with GBIF work differently to that with IUCN?

@helendallas

**Comment by timlinux** [comment]
Could you add a proper description for this @jeremyshelton ?

**Comment by dimasciput** [comment]
@jeremyshelton please test this feature on live site.

**Comment by jeremyshelton** [comment]
@dimasciput this button is not doing what was requested. 

We requested a button that pulls in the new GBIF occurrence data for example when a new taxon is added (unless this is something that happens automatically?)

However, what the button currently does is takes the user to the GBIF page for that taxon.

@helendallas

**Comment by helendallas** [comment]
@jeremyshelton @dimasciput 
No this is what we asked for. The harvesting of GBIF data is done in a completely different work flow. 

This is to add the GBIF link to the taxon in Taxon Management.

We need a training session soon.

I will create another tutorial as well. Please also read the notes I sent you a while ago on data management etc. I will add them all to dropbox

**Comment by jeremyshelton** [comment]
@helendallas OK understood, but if you look at the top of this ticket, the feature request is 'adding a 'Find GBIF' button in taxon management, just like the one for 'Find IUCN' - something that would allow us to easily pull GBIF data when a taxon is changed or a new taxon added?'

**Comment by dimasciput** [comment]
@jeremyshelton the find iucn button is also in the admin page. You can go to this page from taxon management.

**Comment by helendallas** [comment]
@jeremyshelton My understanding of the ticket was to allow a taxon to be linked to the IUCN page, and or the GBIF page. What has been implemented is allowing the GBIF id to be populated, one then uses the front 

![image](https://user-images.githubusercontent.com/45286876/122049643-f2846d00-cde2-11eb-923d-3dc855effe28.png)


so when you click here IUCN - 
https://www.iucnredlist.org/species/2427/99448983

and GBIF: 
https://www.gbif.org/species/2339006

If there is no GBIF or IUCN link - Then if one edits the taxon and these are shown:
![image](https://user-images.githubusercontent.com/45286876/122049914-3c6d5300-cde3-11eb-9ba8-5c8decdad4ef.png)

If GBIF is blank, the Find GBIF allows one to find the GBIF number, but one needs to be careful as sometimes the best match is returned, e.g Schilbe returned for Schilbe depressirostris since the latter is not on GBIF

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput 
Understood and agreed. In that case, looks like the button works as and the ticket can be closed.
We can discuss the process of pulling data for a newly added taxon at our next catchup 👍

**Comment by helendallas** [comment]
Excellent thanks @jeremyshelton and @dimasciput
