### ISSUE TITLE
Duplicate (>1) peer-reviewed scientific articles in Source References

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2783]
Some source references have more than one , e.g. the are 3 of Part B of this paper, each with records attached.

https://freshwaterbiodiversity.org/source-references/?collectors=1249&page=

![image](https://user-images.githubusercontent.com/45286876/134191458-a32463aa-5755-48d2-a525-e166d1726386.png)

This seems to be a recurrent issue

**Comment by dimasciput** [comment]
@helendallas I just checked the data, and they have different details, one of them have full detail like number, page, and correct date:

![2021-09-22_08-46](https://user-images.githubusercontent.com/1979569/134270532-bd2785f0-06a0-4a0d-abc3-24cd03045d10.png)

And the other one does not have these data. That's why duplicates occur.

This data comes from third party sources, so it's not a bug of our system, but maybe we can improve the script to look for duplicates when fetching data from third parties.

**Comment by helendallas** [comment]
ok thanks, if I make the source references the same will they merge?

**Comment by helendallas** [comment]
@dimasciput But I don't understand. These data are all linked to the same DOI, which is the same on all source references, we don't add in page numbers etc

**Comment by dimasciput** [comment]
@helendallas it's not from us, the data came from the third party.

**Comment by helendallas** [comment]
@dimasciput Okay, so how do we merge these as they are clearly the same paper. And I suspect there are other examples of duplication in peer-reviewed scientific articles

**Comment by dimasciput** [comment]
@helendallas this was fixed on the live site, there should be no more duplicates for peer-reviewed reference.

**Comment by helendallas** [comment]
Thanks @dimasciput Looks good, closing ticket
