### ISSUE TITLE
Please check the upload Start and End Times

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2951]
I am not sure these are working properly anymore as I tried to upload data that started at 18:00 and ended at 23:00 but it gave me an error message.

![image](https://user-images.githubusercontent.com/45286876/154669347-4e286f6d-8307-435a-ab28-ba7a9ea5a1b5.png)

**Comment by helendallas** [comment]
@dimasciput Yes, I didnt screenshot though . I will try do it again and copy it....

**Comment by helendallas** [comment]
Ok, I reran using data for a month, starting at 18:00 , ending at 23:00

![image](https://user-images.githubusercontent.com/45286876/154672170-23d23eb7-e556-451e-a817-f0775f5af4c4.png)

Here is the file as an xls.
[Start End time test.xlsx](https://github.com/kartoza/django-bims/files/8096630/Start.End.time.test.xlsx)

**Comment by helendallas** [comment]
I did the above on testing but had the same error on live

**Comment by dimasciput** [comment]
@helendallas yes it's because only the first data started at 18:00, next period started at 0:00, that's why you get these errors. 
![image](https://user-images.githubusercontent.com/1979569/155069890-e20d392a-381f-4bc8-a86a-14d96c2a8c24.png)

The easiest solution is for the user to separate these data into two files.

**Comment by helendallas** [comment]
Ok thanks @dimasciput So basically there must be a fill 24h worth of data, so that each day starts at the same time. I will add to upload notes. Closing ticket.
