### ISSUE TITLE
Please can you find a way to upload water temperature data that is more than 12 months long

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2952]
At the moment the system does not work if the time series data are more than 1 years worth. We have several sites where the data are at least 2 years, sometimes longer.

Please can you find a way to allow the upload of water temperature time series data that is > 1 year long.

Here is an example of data that are >24 months
[WT_E1OLIF-ABBUL_19_11_2008 to 10_02_2011.xlsx](https://github.com/kartoza/django-bims/files/8097003/WT_E1OLIF-ABBUL_19_11_2008.to.10_02_2011.xlsx)

**Comment by Fanevanjanahary** [comment]
Hi @helendallas the system can upload data more than a year, I've tried [WT_E1OLIF-ABBUL_19_11_2008 to 10_02_2011.xlsx](https://github.com/kartoza/django-bims/files/8097003/WT_E1OLIF-ABBUL_19_11_2008.to.10_02_2011.xlsx) and it doesn't work since there are 2 days which they are mission row (the first and the last days) I've removed them and it works.

**Comment by helendallas** [comment]
Hi @Fanevanjanahary 
Sorry I dont understand what you mean by mission rows? Please can you explain, thanks

**Comment by dimasciput** [comment]
@helendallas I think she meant missing rows

**Comment by helendallas** [comment]
Ok thanks @dimasciput I will test again

**Comment by helendallas** [comment]
Thanks @Fanevanjanahary @dimasciput I checked this now and it is working. Excellent.  Please roll out to live
