### ISSUE TITLE
We need to be able to monitor downloads of graphs and csv

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2985]
At the moment we keep a record of Download requests, and User Sign ups.

![image](https://user-images.githubusercontent.com/45286876/160068599-93ab745a-9799-4357-bc3c-a4f10d26e09f.png)

We do not have a way to monitor what graphs a user downloads. Please can @timlinux and @dimasciput explore options for this for sprint 6

**Comment by jeremyshelton** [comment]
@dimasciput @timlinux one option is to ask the user what their use for the data is, in terms of reference categories (a compulsory step prior to downloading), and then an option to add more details about the output.

<img width="209" alt="Screen Shot 2022-03-31 at 8 29 54 AM" src="https://user-images.githubusercontent.com/44292029/160990898-320fbc42-0d04-4531-b7f4-a1fe3db8445e.png">

**Comment by timlinux** [comment]
Maybe one more option for 'Other' or 'No specific use'

**Comment by helendallas** [comment]
Yes I think its needs to be a bit more specific than reference category

- Scientific article
- Report
- Thesis
- Presentation
- Proposal
- No specific use


Is it possible to make this something that we as Administrators can change as needed.

**Comment by timlinux** [comment]
For this ticket we will build a table on the backend with this structure:

Date | User id | Resource Type | Resource Name | Taxon | Site |  Survey |Purpose | Dashboard 
------|------------|---------------------|-------| ----------|-------|---------|-----------|-------------|
22-04-2022 | 1 | Chart | SASS Charts  | | |Presentation| https://testing.healthyrivers.kartoza.com/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[19.775390625000004,-33.59631896113268],[20.5224609375,-33.449776583118435],[20.083007812500004,-33.961586289799094],[19.775390625000004,-33.59631896113268]]&thermalModule=&dst=
22-04-2022 | 2 | CSV | SASS Summary   | | | Report|https://testing.healthyrivers.kartoza.com/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[19.775390625000004,-33.59631896113268],[20.5224609375,-33.449776583118435],[20.083007812500004,-33.961586289799094],[19.775390625000004,-33.59631896113268]]&thermalModule=&dst=
22-04-2022 | 3 | Chart | Origin Chart   | Galaxias zebratus | | Thesis | https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=Galaxias%20zebratus&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=
22-04-2022 | 3 | Chart | Conservation Status  |  |21251 | No specific use | https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=Galaxias%20zebratus&siteId=21251&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=21251&orderBy=name&polygon=&thermalModule=&dst=


@helendallas Does this match what you had in mind more or less

What should we do with public users? Should we just store the same info but with the user id empty

Once we have this table populating, we can backtrack their org details from their user id.

There are actually quite a lot of nuances to deal with here - each dashboard can have different generation routes e.g. filtering, lassoo selection and reflecting this in the table (other than showing the whole url like we propose above) may be hard. Even storing the whole url may not reflect the original search well in the future since the criteria in the URL may catch more data as the dataset changes over time.

Once we have this table populating then we can generate charts etc in Metabase.

Along with this ticket and #2986 we looked at the audit tables which we were hoping to pull stats from, but they a) dont store a complete persistent history b) get really large if we do persist the data and c) are difficult to unpack into meaningful data. As such we propose to deprecate the easy audit tracker to keep the system free of baggage code.

We estimate this is going to take about 3 days of Faneva's time to implement the above. Before we start working on it, it would be great for you to sanity check the proposed table above (@helendallas and @jeremyshelton) and let us know if it encapsulates the info you are looking to track well.

**Comment by helendallas** [comment]
Thanks @timlinux I am afraid I am a bit confused why these 4 FBIS queries are here and how they will be used to in reference to this ticket.

In this ticket we just want a pop up message that asks a user what they intend using the data/graph/table for: 
Then the user selects on of the following from a dropdown list that we need to be able to manage and update

-     Scientific article
-     Report
-     Thesis
-     Presentation
-     Proposal
-     No specific use
-
This then gets stored in a place on the FBIS admin that we can access. The same way the Download Requests are currently available.

**Comment by timlinux** [comment]
@helendallas The 4 queries are just different example use cases of where a user might be downloading images or CSV files, and the columns in the table are intended to provide sufficient detail to allow you to contextualise what kind of resources people have downloaded and what they searched for to arrive at the download. The intention is to do as you request in your last post above, and show the user a list of options, then wrote their response along with the context of what they were doing into the logigng table. We can then ask questions like 'how many SASS CSV products were downloaded' etc. Or just browse the table as  alist of events.

**Comment by helendallas** [comment]
Thanks @timlinux but this ticket is about adding a pop up form that a user has to complete when they download a graph or csv file.

**Comment by jeremyshelton** [comment]
@helendallas 

What about including Conservation planning & management, Environmental Impact Assessment, Other (detail in notes), Educational resource...in addition to the below?

Scientific article
Report
Thesis
Presentation
Proposal
No specific use

**Comment by timlinux** [comment]
Hi @helendallas 

>Thanks @timlinux but this ticket is about adding a pop up form that a user has to complete when they download a graph or csv file.

Yes I do understand that. When they download a chart or CSV, the data needs to be stored in our back end system recording who downloaded what - otherwise we cannot generate any meaningful report from the interactions. The table I showed is what we would store on the backend with examples of how we would record downloads of different types of resources. I hope that makes sense now?

Regards

Tim

**Comment by timlinux** [comment]
Apologies I was not explicit in saying that the table would be a backend table that gets added to after the user fills in the popup when they download a resource.

**Comment by helendallas** [comment]
I don't understand what I am seeing when I click on this link

This is what I get
![image](https://user-images.githubusercontent.com/45286876/170029102-429fb3bc-8720-4d7a-9a3e-fa1ec8634402.png)
then
![image](https://user-images.githubusercontent.com/45286876/170029070-e7f1ab17-927b-48b3-91ec-a8f21c3ad9a9.png)

**Comment by dimasciput** [comment]
@helendallas try download any graph in the dashboard, it will show you the pop up form with download purpose dropdown. And you can add more option from **Download Request Purpose** admin page. 
If you want to see the list of downloads go to this link https://testing.healthyrivers.kartoza.com/admin/bims/downloadrequest/.

**Comment by helendallas** [comment]
Thanks @dimasciput I have gone through each dashboard, all working with pop up showing except:

Physico-chemical dashboard
Download as CSV

**Comment by helendallas** [comment]
These all seem to be working, except, the Physico-chemical dashboard

![image](https://user-images.githubusercontent.com/45286876/173337712-6f337e9f-374b-47d3-9ccb-459e0c684e19.png)

Download as csv

![image](https://user-images.githubusercontent.com/45286876/173337760-f782226a-3215-4fc9-821f-639453bea8a3.png)

https://freshwaterbiodiversity.org/physico-chemical/11056/?taxon=&search=&siteId=11056&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=True&ecologicalCategory=&rank=&siteIdOpen=11056&orderBy=name&polygon=&thermalModule=&dst=

Once this has been added, I can close the ticket.

**Comment by helendallas** [comment]
Thanks, physico-chemcial graph now working but the csv download is not. I do not get asked what I intend using it for. Please check again.

![image](https://user-images.githubusercontent.com/45286876/179915196-815bb34c-c484-42c7-9d22-992fda26c736.png)

https://testing.healthyrivers.kartoza.com/physico-chemical/30704/?taxon=&search=&siteId=30704&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=True&ecologicalCategory=&rank=&siteIdOpen=30704&orderBy=name&polygon=&thermalModule=&dst=

**Comment by helendallas** [comment]
I am closing this ticket. Mostly done
