### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3175]
Hi @dimasciput 
We have started playing around with the mobile App. 
Looking pretty good so far. 
Here are some issues and suggestions:

![Screenshot 2022-08-24 at 12 14 34](https://user-images.githubusercontent.com/44292029/186393295-02edfe8c-ba2f-4878-a314-9b792464386e.png)

Looking forward to seeing the next iteration including the SASS workflow...

@helendallas @aneriswanepoel @timlinux

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput - just as long as it is easy for a user to easily add data to the site that they have just created. 
When we were testing it it was no straightforward to find a site that had just been created. Maybe it should automatically give the 'add data' options as the next step after site created?
@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton 
> Maybe it should automatically give the 'add data' options as the next step after site created?

I just added that here https://github.com/kartoza/mobile-bims/pull/12, you can see the video there. 
Hopefully at the next sprint, I can give you the updated app.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput  - looks good.
Looking forward to seeing the next version.

**Comment by jeremyshelton** [comment]
@dimasciput here is an updated list of issues and requests, based on the most recent version of the mobile app.
Let us know if clarity is needed on any of these points. 

[FBIS App Feedback - 23 Jan 2023.xlsx](https://github.com/kartoza/django-bims/files/10477766/FBIS.App.Feedback.-.23.Jan.2023.xlsx)

@helendallas @timlinux

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas 

> Add the FBIS rivers layer

We can show this, but when the device is offline the layer will not be updated, since it needs internet. Should we go ahead? 

> Search bar is not working

We can only search site codes, because we didn't download all the occurrences from the server, only nearest sites. 

> Load map (Bing satellite) and sites for selected area in advance. We would like to be able to draw a polygon around the area of interest so that the map and sites will be pre-loaded so that they are available when offline. 

Can you explain the workflow? 
I'm going to try the pre-loaded map feature, but it might take some time, and are we going to download all the zoom levels?

**Comment by jeremyshelton** [comment]
Thanks for the feedback @dimasciput 

1. Rivers layer: OK. That might work. Could we perhaps give the user an option to pre-load the rivers layer for a polygon of interest? (see point 3 below).
2. OK.
3. The idea here is when a user is still online for them to have an option to draw a polygon around an area of interest and be able to download the map, rivers layer and sites so that they are available and visible for that area when viewing the map offline. I think it would need to be for all zoom levels. [GaiaGPS](https://www.gaiagps.com/map/) is that app that I use in the field and being able to download maps for selected areas for use offline is extremely helpful. 
However, we don't want to do this if it is going to significantly eat into your app development time. If that's the case I'd rather put this feature request on the back-burner and implement it if we have time later in the budget. 

@helendallas

**Comment by jeremyshelton** [comment]
@dimasciput do you have a new version of the mobile app for us to test yet?

**Comment by jeremyshelton** [comment]
@dimasciput do you have a new version of the mobile app for us to test yet?
@helendallas

**Comment by dimasciput** [comment]
Hi @jeremyshelton , I'm offline today, I will check tomorrow.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput

**Comment by jeremyshelton** [comment]
@dimasciput we are waiting for feedback from user testing. 
Will revert next week. 
Then the next step will be to finalise, deploy to iOS and release the app to the FBIS user community.

**Comment by jeremyshelton** [comment]
@dimasciput here is the feedback from the App testing:

**Offline download**
•	New functionality request: to download sites for offline area

**Adding a site**
•	Capturing an image: Standardise across modules (currently taxa aork flow allows to delete photo but sass work flow does not). 
•	Search bar: Search bar should say (and do): “Search site code” only
•	Site code: Option to add “User site code”. Then the user should see the FBIS site code after they add a site.
•	River name: Currently river name is blank, but it should show the river name that FBIS finds (when online only) – can we show the user what this is and also allow users option to add original river name?
•	User email: Generate user email with csv with new site information after they create a new site using the app. 
•	Bug: site description becomes site code (which it should not). In field use the “user site code” until the FBIS site code gets generated by FBIS?

**Comment by jeremyshelton** [comment]
@dimasciput we are having trouble installing the latest version of the FBIS app. When trying to install it gets stuck when loading the map. We have tried on two different phones…

![WhatsApp Image 2023-08-22 at 14 03 43](https://github.com/kartoza/django-bims/assets/44292029/7789a920-f658-4878-aa70-993dd85f118a)

**Comment by dimasciput** [comment]
@jeremyshelton @KSnaddon @helendallas 

> Adding data to a site
> Source reference dropdown is limited to only two options (FRC and CapeNature) - should there not be the full list of source reference options available? Is this not what should be on offer?

You need to set this in the admin panel. We don't want to show all the source references because it would be too much. I believe we've already had this discussion.

<img width="1278" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/d6293746-00ea-4eba-b54c-5fec698ecad0">

> Data syncing
> The app automatically downloads taxa, SASS, sites etc after syncing a new record - I don't think that these syncs should happen automatically?

Why not? We also need to download from new sites to update the site codes.

> Add Record
> When adding an observed taxon, the checkbox on the right should include these options?

I believe we've already had this discussion. I think we want simplicity and just use numbers for this. Maybe we can add these options in the next version? It will take more time to update the API in the backend and also update the app.

> User email
> We tested this and the user did not receive an email after adding a site?

I received this email, please check the spam folder, since we are using the testing site.

<img width="925" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/d80dfe61-2b2c-481e-9939-fb31277b606a">


@jeremyshelton, @helendallas, @KSnaddon: I suggest we refrain from adding new features, such as in 'abundance type', since it would increase the workload for the iOS port. Let's focus on completing this version, fixing any bugs, and then releasing it. We can always introduce new features and update the app later. What do you think?

**Comment by jeremyshelton** [comment]
Thanks for the feedback @dimasciput
Agreed lets get this version working perfectly and then release so that you can move on to other tickets. 

In my opinion it is important to sort out the two below-mentioned points before we release - see my suggestions below. The other issues are fine for now, but just remember to update the search bar prompt text.

**Add Record**
OK fine to have just the abundance option, but can you just include something to tell the user that this is where they can enter an abundance value? It is not obvious?

**Adding data to a site**
Source reference dropdown is limited to only two options in the current dropdown (FRC and CapeNature). Can we not include all of the existing database options currently on the FBIS, and the option for a user to add a new database?

**User email**
@KSnaddon please check your spam folder and revert?

**Comment by dimasciput** [comment]
@jeremyshelton 

> OK fine to have just the abundance option, but can you just include something to tell the user that this is where they can enter an abundance value? It is not obvious?

Yes this is possible. 

> Source reference dropdown is limited to only two options in the current dropdown (FRC and CapeNature). Can we not include all of the existing database options currently on the FBIS?

As I mentioned earlier, you have the option to select which source references are available for mobile through the admin page. Please follow these steps:

- Navigate to the admin page: [https://testing.healthyrivers.kartoza.com/admin/bims/sourcereference/](https://testing.healthyrivers.kartoza.com/admin/bims/sourcereference/)
- Select a source reference, for example, 'River database'. Direct link: [https://testing.healthyrivers.kartoza.com/admin/bims/sourcereference/1258/change/](https://testing.healthyrivers.kartoza.com/admin/bims/sourcereference/1258/change/)
- Check the 'mobile' box.
![Screenshot](https://github.com/kartoza/django-bims/assets/1979569/814ba9b3-4eab-47af-a02c-4f15cc059c55)
  
- Finally, click 'Save'. Afterward, you'll need to click 'Sync' in the mobile app."

Let me know if it doesn't make any sense.

> option for a user to add a new database?

Unfortunately, this wasn't part of the initial requirements. Introducing it at this stage will require at least a day because I'll need to update the sync functionality, incorporate a new form for the source reference, and add further validation. I believe it would be more efficient to add the source reference directly in the site.

**Comment by KSnaddon** [comment]
@jeremyshelton  Nothing in spam.

**Comment by jeremyshelton** [comment]
@dimasciput ok sounds good. So still todo:

**Dimas**
1. Add abundance label to 'Add a record' so users know what to do
2. Fix user email (Kate did not receive an email after adding a record with app. Not even in spam folder)

**Jeremy**
Update mobile app source references using admin page

Sound good?

**Comment by dimasciput** [comment]
@KSnaddon is this your email?

<img width="1057" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/11d08195-ed55-4923-8034-e44f2f3ee7fc">

**Comment by KSnaddon** [comment]
@dimasciput  Yes that is my email address, but I didn't receive that email.

**Comment by jeremyshelton** [comment]
@dimasciput is there perhaps a way to automate that all source references on the FBIS are available on the Mobile App?
It seems inefficient to have to add these all one-by-one, or to add new ones when users create them...

**Comment by helendallas** [comment]
@jeremyshelton I don't think we ant all source reference available . this will be hundreds.

**Comment by jeremyshelton** [comment]
@helendallas yes agreed. 
Sorry - I meant all databases.
Would that make sense?

**Comment by jeremyshelton** [comment]
@dimasciput 
We have tested the latest version of the App.
Here are the issues that we have detected.

1. User cannot add a wetland site outside of a wetland polygon. However, they do need to be able to do this. This applies to Desktop version as well. 
2. Access to phone camera has always been automatically enabled by default in previous versions. This was not the case in the most recent version. This will confuse first time users. Please make access to phone camera a default if possible. 
3. Text scaling issue in the "add site" panel (The text in the green boxes). Please make the text the same side as the 'add site" text. Perhaps making those text boxes longer an only having one per line might help? In short, we don't want the text for one word carrying over to a second line. 
4. Occurrence record photos: can it be possible for users to add up to three photos for each taxa occurrence record. If so please implement. 
5. SASS option should not be available for wetland and open water body (if this is easy to do?). This is because SASS data can only be added to rivers. 
6. Add a record: The prompt text for Add abiotic data needs to be changed from "find abiotic here" to "type parameter name"
7. Same goes for Observed taxa where the prompt text should be changed to "Type taxon name here"
8. If you capture a site image when adding a record, will that be added as an additional image alongside and previous images added when the site was created?

**Comment by jeremyshelton** [comment]
@dimasciput have you been able to address these fixes yet, or will that only happen next sprint?

**Comment by dimasciput** [comment]
@jeremyshelton @KSnaddon @helendallas 

1. How did you obtain the hydroperiod and other information if the site is outside the wetland layer? This information is essential for generating the site code. For river sites, we'll use the closest information. However, I haven't added this function yet. I'll need to implement it in the Geocontext. It will probably take a day. We might also need to upload the wetland layer to a different database so we can calculate the nearest wetland, similar to what we did with the river. That is, unless it's fine for the wetland not to have any wetland data.
2. It's not possible, the previous version also required permission. This is not allowed in both Android and iOS.
8. Yes, it will be added to the existing records for that site.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput 

@KSnaddon @helendallas thoughts on point 1?

Points 2 and 8 OK ✅

**Comment by KSnaddon** [comment]
1. The wetland map is not 100% accurate so users must be able to add points that are not within a wetland polygon.  This goes for the App as well as the FBIS Map.  The site code is generated using the quaternary catchment (from the quaternary catchment layer) and the wetland name (from the Wetland Map, if there is a name, otherwise the User will enter the name).  Surely the App doesn't need to provide the Hydrogeomorphic Type (I assume you mean this @dimasciput and not the hydroperiod, which is data that will be added by the User) etc?  What other information is required??

**Comment by dimasciput** [comment]
@KSnaddon, there's wetland data stored on the site that's hidden from the frontend, but you can access it on the admin page. However, if this can be left blank, then we don't need to check whether the site is inside a wetland. I will make the updates.

> The site code is generated using the quaternary catchment (from the quaternary catchment layer)

I actually used quaternary name from the wetland layer, but I will change this to use quaternary layer.

**Comment by KSnaddon** [comment]
@dimasciput Yes that makes sense to use the quaternary catchment layer rather.  Apologies, I should have suggested this!



> @KSnaddon, there's wetland data stored on the site that's hidden from the frontend, but you can access it on the admin page. However, if this can be left blank, then we don't need to check whether the site is inside a wetland. I will make the updates.

Are you talking about the Mobile App here? I do understand about the information only accessible on the admin page, but didn't think that hydroperiod etc is on the App?

**Comment by helendallas** [comment]
@dimasciput Please see **FEEDBACK** below


- User cannot add a wetland site outside of a wetland polygon. However, they do need to be able to do this. This applies to Desktop version as well. **WORKING ON APP**
- Access to phone camera has always been automatically enabled by default in previous versions. This was not the case in the most recent version. This will confuse first time users. Please make access to phone camera a default if possible. -  **THIS IS STILL BLANK. **CAN YOU SET IT THAT ON ISTALLATION THE USER IS ASKED FOR PERMISSION TO SUE THE CAMERA  LIKE IT DOES FOR LOCATION**IF IT CANT BE CHANGED WE NEED TO INSTRUCT THE USER WHAT TO DO** 
- Text scaling issue in the "add site" panel (The text in the green boxes). Please make the text the same side as the 'add site" text. Perhaps making those text boxes longer an only having one per line might help? In short, we don't want the text for one word carrying over to a second line. **OPEN WATERBODY IS STILL TRUNCATED BUT THINK IT IS FINE**
- Occurrence record photos: can it be possible for users to add up to three photos for each taxa occurrence record. If so please implement. From Helen - yes you can take more than one photo already **FINE**
- SASS option should not be available for wetland and open water body (if this is easy to do?). This is because SASS data can only be added to rivers. **SASS OPTION HAS DISSAPEARED FOR RIVERS????**
- Add a record: The prompt text for Add abiotic data needs to be changed from "find abiotic here" to "type parameter name"  **DONE**
- Same goes for Observed taxa where the prompt text should be changed to "Type taxon name here" **DONE**
- If you capture a site image when adding a record, will that be added as an additional image alongside and previous images added when the site was created? **YES THIS WORKS**

**NEW**
**@KATE @jeremyshelton Biotope/habitats not correct because production site hasn't mirrored onto the testing. I have updated all on production.** should work fine once mirroring has happened
**NEW TEXT UNDER ECOSYSTEM TYPE: RIVER CANNOT BE READ USERNAME, RIVER NAME, LAT LONG.......MAYBE LEAVE OUT OR SHIFT LAT LONG TO SECOND LINE**

**Comment by dimasciput** [comment]
@helendallas 

> Access to phone camera has always been automatically enabled by default in previous versions. This was not the case in the most recent version. This will confuse first time users. Please make access to phone camera a default if possible. - THIS IS STILL BLANK. CAN YOU SET IT THAT ON ISTALLATION THE USER IS ASKED FOR PERMISSION TO SUE THE CAMERA LIKE IT DOES FOR LOCATIONIF IT CANT BE CHANGED WE NEED TO INSTRUCT THE USER WHAT TO DO

Yes, this is what supposed to do if you do a fresh install. Can you uninstall the app and then install it again.

**Comment by KSnaddon** [comment]
@dimasciput At one stage, when you add a site, you could move the site marker on the map that opens when you hit "Add River/Wetland/Waterbody site".  Is this still possible? It was quite handy.

**Comment by KSnaddon** [comment]
My phone doesn't go to the map, and just hangs like this:

![WhatsApp Image 2023-10-05 at 07 46 49_3aa3a901](https://github.com/kartoza/django-bims/assets/91128958/28fec58a-d5e4-42e2-9adc-708bc0654f14)

**Comment by dimasciput** [comment]
@KSnaddon there was issue with river layer, can you try it again now.

**Comment by KSnaddon** [comment]
@dimasciput Working now

**Comment by KSnaddon** [comment]
@dimasciput Two quick comments on the Mobile App:
1. Wetland map is no longer visible when you add a site
2. I'm sure at one point I could move the pointer to a site, rather than just accept the co-ords of my current location.  Is this no longer possible?
3.  The plant module drop-downs are still unspecified. @helendallas will you and I update this on FBIS and then will it come through to the Mobile App?

**Comment by helendallas** [comment]
Latest testing 10 Oct @ 10h00,. SA time

User cannot add a wetland site outside of a wetland polygon. However, they do need to be able to do this. This applies to Desktop version as well. This was fixed but no get Error. Wetland data not found.
Fetch wetland does not seem to be working even when a site is created in a polygon - it is either blank, or get error message

When I tried to synchronise I got error
One of the data can't be synchronised

So nothing was synchronised.

**Comment by dimasciput** [comment]
Hi @KSnaddon @helendallas please try to add the wetland again, there was a bug in the backend.

**Comment by helendallas** [comment]
@dimasciput I have reinstalled app. still having problem with Fetch wetland.

**Comment by dimasciput** [comment]
@helendallas, you need to ensure you are inside the wetland layer. If you're not, then you won't receive wetland data.

**Comment by dimasciput** [comment]
> @dimasciput Still getting error message when I try to add a wetland to a site that is not in a wetland polygon. DO I need to uninstall and reinstall app?

@helendallas can you try it again?

**Comment by helendallas** [comment]
I still get nothing returned when I click in a wetland polygon and click fetch wetland.
Then if I click outside a polygon I get error message if I click fetch wetland, but perhaps this normal as there is no polygon. Not sure if a user will do that?

**Comment by helendallas** [comment]
Ok, So when I click in a wetland polygon no wetland name is returned. Perhaps @KSnaddon can try later today and feed back to you by Friday.

**Comment by KSnaddon** [comment]
@helendallas @dimasciput The Wetland layer generally doesn't have a name for the wetland, which is why the user entered name should override this.  So it will often be blank after  hitting "Fetch wetland".  

It is really important that the user can add a wetland site without being inside a wetland polygon.  I know that this means some of the context data on the panels (i.e. anything pulled from the wetland map) will be blank.

**Comment by helendallas** [comment]
@KSnaddon Thanks. Maybe I was clicking on wetlands that didn't have a name. A user is able to add a name easily. @dimasciput if Kate has nothing further then should be all working

**Comment by KSnaddon** [comment]
@dimasciput If I try and add biodiversity data on the App, the drop-downs are all "Unspecified".  Is this a bug or just waiting to synch with the upload options that you get on the FBIS platform?

**Comment by helendallas** [comment]
@KSnaddon As per previous comment, you won't see the dropdown until the testing site has been mirrored to production. I only updated dropdowns on production

**Comment by dimasciput** [comment]
@KSnaddon @helendallas the production database has been restored to testing. Please give it a test.

**Comment by KSnaddon** [comment]
@dimasciput It is still "Unspecified" on the Mobile App

**Comment by dimasciput** [comment]
@KSnaddon for which module? Have you reinstalled?

**Comment by helendallas** [comment]
**Some issues:**

When adding plant data

- Hydroperiod: only see n, a, r in dropdown
- Broad biotope - All there now Kate. Not specified is there in addition to Unspecified (even though this is not in biotope-broad bias table
- Specific biotope - Not specified (Kate you said there were no specific biotopes for plants
- Substratum - 3 options
- Sampling method - also Not specified and Unspecified even though only Unspecified is in Bims table

So generally for other modules as well Not Specified and Unspecified ar there......@dimas should I remove Unspecified from BIMS for all?

**Comment by KSnaddon** [comment]
@dimasciput Did you send another release?

**Comment by KSnaddon** [comment]
@dimasciput @helendallas Sorry it's "Not specified" that I get on the App.  I installed the version that was sent last week, so perhaps need to re-install?

**Comment by helendallas** [comment]
@dimasciput If I delete Unspecified, it has records associated with it, so I cannot. We used unspecified in the Upload templates. Please advise what the solution is here so that we have either Not specified, or Unspecified. NOT BOTH.

**Comment by dimasciput** [comment]
Thanks, updating the mobile app today.

**Comment by helendallas** [comment]
Please see #3563 for details on action for Not specified and Unspecified

**Comment by helendallas** [comment]
I hate to do this but I just realised we have left out Sampling effort in the App.  It means that species data added in the field won't populate all fields in the FBIS production.


@dimasciput How easy/hard is it to add this at this late stage. We would need to add Sampling Effort (In Bims as Sampling Effort Measure) and then a place to capture the minutes or time or replicates

@jeremyshelton thoughts?

<img width="957" alt="Screenshot 2023-10-25 at 11 11 40" src="https://github.com/kartoza/django-bims/assets/45286876/4c587bf0-29a7-425c-b5e6-0f93e34e8a76">


<img width="280" alt="Screenshot 2023-10-25 at 11 17 35" src="https://github.com/kartoza/django-bims/assets/45286876/2afb7236-7567-440a-9ff1-8fede5c3c856">

**Comment by dimasciput** [comment]
@helendallas probably 3-4 hours

**Comment by helendallas** [comment]
Ok I think we should do it please @dimasciput

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput from my perspective this is critical for the mobile app.

**Comment by KSnaddon** [comment]
Agreed!

**Comment by helendallas** [comment]
### **Final checks and notes**

The GBIF Test module was added to the app. @dimasciput When we create a new module, is there a way for us to say, Include on App. This seems like it is needed going forward.

**Systematic checks**

Adding a new river site - success
Adding a new wetland site - success
Adding a new open water body site - success

Adding fish data - fish data added to G2SCHU-00175 river site, - success
Adding anuran data - **I got an error when I tried to sync anuran data added to a wetland site** Please check @dimasciput 
Adding plant data - sometimes it worked, other times I got an error not able to synchronise, this was plant data added to an open waterbody site after I had added anuran data.

I tried to replicate the error. If I leave everything unspecified but just add a taxon, then I get the error
If sampling effort is unspecified, the data don't sync

The after that I added new data but it just spun.
Then I logged out, and couldn't log back in.

Think system is down? Stopping now.

**Comment by helendallas** [comment]
Final check before release:

- Add River. -add site, add fish, add anuran, add plants, add SASS - all working
- Add wetland - add site, add fish, add anuran, add plants, add SASS - all working
- Add open waterbody - all working
- Download river and site - working
- List unsynced sites - working
- Clear data - working
- Search for site - working

**One Comment:** If a user adds a wetland site, outside the current wetland polygons - and clicks " fetch wetland" , then an error message is returned: "**Error wetland data not found**". Maybe this should not be an error message but rather a prompt to  **Please add User Wetland Name**. @KSnaddon what do you think?

**Comment by jeremyshelton** [comment]
Good stuff.
I agree with the below.

_Maybe this should not be an error message but rather a prompt to Please add User Wetland Name. @KSnaddon what do you think?_

**Comment by helendallas** [comment]
@dimasciput Ignore reference to #3587 

Please just change error message to a prompt as detailed above.

If a user adds a wetland site, outside the current wetland polygons - and clicks " fetch wetland" , then an error message is returned: "Error wetland data not found". Maybe this should not be an error message but rather a prompt to Please add User Wetland Name.

**Comment by helendallas** [comment]
Final comments undertaken via email. Final version released and being added to play store etc. Closing this ticket now

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas I have tested the latest version and there are some small fixes that I feel are needed before we finalise the app. So, I suggest holding off on releasing the final version until you've looked through these.

Helen I've sent these to you via email to look through first before sending to Dimas.

**Comment by dimasciput** [comment]
Hi @jeremyshelton @helendallas, I recommend starting a new ticket for this issue for better tracking. If the original ticket's issues are resolved, please consider closing it.

**Comment by jeremyshelton** [comment]
@dimasciput OK - final fix requests are listed in ticket #3637
