### ISSUE TITLE
Monthly average temperature columns jumbled in CSV data downloads 

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3361]
@dimasciput  he order of the monthly average temperature columns in csv download files is jumbled. Example attached.
@helendallas  is the csv data download the correct place for these monthly thermal metrics? If so, can we perhaps group them all at the end (far right) of the csv file?

[bd5f71895931eb418224742cdf306493c2401dd396d8b8d8f5587ff2a501d387.xlsx](https://github.com/kartoza/django-bims/files/11248163/bd5f71895931eb418224742cdf306493c2401dd396d8b8d8f5587ff2a501d387.xlsx)

**Comment by dimasciput** [comment]
This is deployed to testing and production

**Comment by jeremyshelton** [comment]
@dimasciput 
I can't test this on production site because the dashboard is not allowing me to query more than one month of data, despite there being several years worth of data at this site: https://freshwaterbiodiversity.org/water-temperature/9980/2011/?taxon=&search=&siteId=9980&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22%2C%22gbif%22%2C%22virtual_museum%22%5D&module=water_temperature&ecologicalCategory=&rank=&siteIdOpen=9980&orderBy=name&polygon=&dst=&startDate=2011-01-01&endDate=2011-02-01

**Comment by dimasciput** [comment]
@jeremyshelton you can query for more than one month, but you can't choose more than one year because the dashboard operates on a yearly basis. Here's example for 1 January to 31 December :

https://freshwaterbiodiversity.org/water-temperature/9980/2011/?taxon=&search=&siteId=9980&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=&validated=&sourceCollection=%5B%22fbis%22%2C%22gbif%22%2C%22virtual_museum%22%5D&module=water_temperature&ecologicalCategory=&rank=&siteIdOpen=9980&orderBy=name&polygon=&dst=&startDate=2011-01-01&endDate=2011-12-31

**Comment by jeremyshelton** [comment]
@dimasciput for me the graph only shows one month data, even though the data selection is a year - is that correct?
Also, can you remind me where to download the csv? I don't see that option here.

<img width="943" alt="Screenshot 2023-06-27 at 09 50 48" src="https://github.com/kartoza/django-bims/assets/44292029/cd0f15e5-0706-4361-8a28-2531c7ecaae8">

**Comment by jeremyshelton** [comment]
All sorted now.
Thanks @dimasciput

**Comment by helendallas** [comment]
@jeremyshelton The monthyl data from csv does not relate to the thermal dashboard. Assume you spoke to @dimasciput and he explained

**Comment by jeremyshelton** [comment]
@helendallas yup - all sorted
