### ISSUE TITLE
Error with red outlines on filters

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3362]
Red filter outlines not matching filter selection.

<img width="1323" alt="Screenshot 2023-04-26 at 06 38 05" src="https://user-images.githubusercontent.com/44292029/234472581-0b46752c-d89a-464c-88b2-1ff5261e73d2.png">

**Comment by dimasciput** [comment]
@jeremyshelton it seems we just need to reharvest the geocontext data. I will do that with the new protected area layer too.

**Comment by helendallas** [comment]
@dimasciput 

I am curious why this happen, where a filter is applied bu we get sites outside the selected area. This has happened before and is a problem as a user may not realise and the selects the sites overview and data without realising they have sites outside the filtered area. It must be something to do with geocontext not working correctly?? Why does it need to reharvested?

Please can you check and explain why this is happening and think about what needs to be done to avoid this going forward.

![image](https://github.com/kartoza/django-bims/assets/45286876/33d4c10d-fb91-4998-b1bc-2661e477af4f)

**Comment by dimasciput** [comment]
Hi @helendallas ,

The problem comes from:

1. The site changing its coordinates, or the geocontext data being updated and we haven't yet applied these updates to the sites.
2. I've also discovered a bug in the geocontext harvest script. If previous data had an 'X' value for the spatial filter, and when we rerun the script the new data is None or missing, it won't update the site. So, the site continues to use the 'X' value.

I've already fixed issue number 2, but regarding issue number 1, there's no direct link between Geocontext and FBIS currently. When Geocontext is updated, FBIS doesn't automatically know—we have to manually trigger the update. Therefore, the only solution I can come up with at the moment is to perform a full Geocontext data update in the background every month.

**Comment by helendallas** [comment]
Thanks for the detailed explanation @dimasciput 

Ok for fixing issue 2.
Agree re automating a full geocontext data update in the background every month. Perhaps set to a sunday evening South African time, when I doubt anyone will be using FBIS.

Please can you action 1, and then close this ticket.

**Comment by dimasciput** [comment]
<img width="1481" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/099a78dc-2bee-473c-86a8-196e90dcfc4d">

Ok I have added a service in the backend to fetch the gecontext monthly, will close this ticket now
