### ISSUE TITLE
Tsk 16. Develop functionality to tag sensitive data and implement a system for different levels of user access

### ISSUE THREAD

**Issue by amyburness** [kartoza/django-bims#3605]
Develop functionality to tag sensitive data and implement a system for different levels of user access.

**Comment by helendallas** [comment]
@dimasciput 

The locality of sensitive taxa should be masked. It should still be on checklists, and included in dashboards etc.

**Comment by helendallas** [comment]
There are also datasets that are private - use Data Type to limit access to certain datasets

**Comment by helendallas** [comment]
@dimasciput Any update on this?

Here we need to be able to label certain taxa as sensitive. The existing attribute added to the Master List and to the taxon Group in the Taxon Management is used to label a taxon as Sensitive. The actual occurrence location for this species needs to be hidden, although the data should be included in the dashboards, csv, checklist.


![Image](https://github.com/user-attachments/assets/9e591585-91b2-4eb4-8502-09db853b7742)

**Comment by dimasciput** [comment]
@helendallas, no, I haven't worked on this yet. So, it will be hidden from all users, correct? Whether they are staff or public, because this is easier to implement, probably take a day.

**Comment by helendallas** [comment]
It will be hidden by all users except the specified users =  sensitive. `again it will be taxon specific.......so User Helen Dallas can see Rhino records....
Dimas can see leopard etc.

The nB is that the data are still included in the dashboards etc, but location is masked, not sure how this will work. Would you use a Park? Do I need to check with Dian and Judith on Wednesday?

**Comment by dimasciput** [comment]
This is quite complicated, and we anticipate a lot of challenges in the future with so many use cases.

- Regarding user-specific permissions, as I mentioned in the other ticket, this is pretty complex. It might take 2-3 days to implement, and it could also impact performance. Additionally, we need to figure out how to assign users to specific taxon groups. Perhaps you can raise this issue with them? If it's not a priority, we could consider it in the next phase.
- Can the species be changed to non-sensitive? If so, this won't happen instantly, the changes will be processed in the background when the user changes the species to non-sensitive or vice versa, depending on the data.
- Location data can be shared with other species that are not sensitive. How should we handle this? Should we still display the location sites?
- Regarding the nb, you want the species to be hidden on the map, but still searchable with results?

This is quite complex for the NB because what you see on the map is a location site, and a location site doesn't have a direct relationship with species. The relationship is: Location site → Occurrences → Taxonomy. Basically, I need to add a new field to the location site, something like "is hidden" or not, which will change based on the taxonomy's sensitivity. So, when the user changes the taxonomy sensitivity, the system needs to update all location sites related to that taxonomy.

**Comment by helendallas** [comment]
Thanks @dimasciput Agreed, quite complex.

Let me discuss with them.

So for now we can - assign certain datasets to public, private (sanparks staff all) or sensitive (only specific individuals.

Not sure about species? I get it is complicated. What would be a workable option for a sensitive species?

**Comment by helendallas** [comment]
SANParks have agreed to focus on #3598 for restricting data access base don Data Type. This ticket can be on backburner for now.
