### ISSUE TITLE
Add unique id to collection record

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#362]
Based on discussion with @timlinux , we should add unique id field to the collection model for validation. 

Add information on how to generate uuid from excel : https://gist.githubusercontent.com/msubel/9c70951a20efe5c72195/raw/14da3b6c8e3401b53d4399590d8b63fd726e60c8/uuid_v4_excel_formula.txt

**Comment by gubuntu** [comment]
why in Excel, why not in the DB (https://dba.stackexchange.com/questions/122623/default-value-for-uuid-column-in-postgres) or with Python?

**Comment by dimasciput** [comment]
@gubuntu maybe @timlinux can answer that? 

But iirc to let user edit their data in csv if the data has incorrect information.

**Comment by cchristelis** [comment]
rather than adding a UUID in the spreadsheet itself, why don't we record metadata around where we got the record? Something like "Spreadsheet, by XYZ on Date, Row 5" should be just as unique as a UUID and also we could use more human-readable text to tell users if the data came from GBIF vs Spreadsheet etc?
