### ISSUE TITLE
13. Develop a tagging system for taxa

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3631]
Key Features to Implement:

- [x] **Tag Creation:** 
Enable creating and managing tags for taxa.

- [x] **Tag Assignment Interface:** 
User-friendly interface for assignin tags to taxa, with search and select capabilities.

- [x] **Data Integration:** 
Seamless integration with the existing database, ensuring data integrity.

- [x] **Search and Filter:**
Enhanced search to filter taxa based on tags.

- [ ] **Documentation:** 
Clear instructions and guidelines on using the tagging system.

**Comment by dimasciput** [comment]
Probably we are going to use this one https://django-taggit.readthedocs.io/en/latest/admin.html

**Comment by helendallas** [comment]
@dimasciput Please provide further comments here on progress - in the email you showed as completed but that's not clear from this ticket

**Comment by dimasciput** [comment]
@helendallas, I believe it's just missing the documentation and tag management. Do we need tag management? We can remove the tag from the taxon, and I think it's fine for now for the admin to remove and manage tags from the admin page. What do you think?

**Comment by helendallas** [comment]
@dimasciput Agreed, we can use current system for removing tags etc.

**Comment by dimasciput** [comment]
@helendallas We might want to consider removing the sorting by tags. There is no requirement for it, and it can be quite complicated since one taxon can have multiple tags. This can be confusing for users, as they may not understand which tags are being used for sorting.

**Comment by helendallas** [comment]
Thanks @dimasciput 

@schmikloi Please see if you can manage with the filtering for tags only, and not actioning sorting for tags. As @dimasciput mentioned, if a species has multiple tags then sorting will be problematic. It is quite easy to use filter to get a subset of taxa that are tagged.

**Comment by schmikloi** [comment]
@helendallas yes, as I said in the call, sorting the tag-column is not necessary...

@dimasciput regarding filtering: if I filter for two tags, they are combined with an OR (so I get all freshwater and all limno-terrestrial); can we implment an option that we combine the tags with an AND, so that I get only those which have both tags?

I am asking this because I am going to propose a variety of environmental tags; we do not necessarily have to have them as tags, if you think another option would be better.

If combining the tags with an AND is not possible we could have more than one tag-coulumn (i.e. one for the water-dependency and one for the environement...). What do you think @helendallas?

**Comment by helendallas** [comment]
This is working fine. Closing ticket
