### ISSUE TITLE
Sites not showing in 'add a site' map

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3803]
@dimasciput sites are not showing in 'add a site' map, but they should be.
https://testing.healthyrivers.kartoza.com/location-site-form/add/?type=River

**Comment by dimasciput** [comment]
@jeremyshelton, you need to click on the map first. Do you want to show the current user location on the map? There will be a permission check popup, and the user will need to accept that. Is that okay?

**Comment by dimasciput** [comment]
Ah, you mean the location sites? Will check this.

**Comment by jeremyshelton** [comment]
Yes. Location sites.
Thanks @dimasciput

**Comment by dimasciput** [comment]
Deployed in testing

**Comment by helendallas** [comment]
@dimasciput I think the issue is if you click on the map, the site you want to add is shown, but only a message alerting you to where nearby sites are pops up. Not the actual sites, So one can't work out if the site is near enough to you won to add your data to.

It would be good if 
A) the ecosystem type is accounted for
b) the nearby sites are shown on the map, so that the use can visualise them and select if desired.

![Screenshot 2024-04-17 at 12 52 39](https://github.com/kartoza/django-bims/assets/45286876/decdeb24-a47e-4c20-a721-26133a46b6ef)


![Screenshot 2024-04-17 at 12 52 50](https://github.com/kartoza/django-bims/assets/45286876/00978a62-6423-49f7-abec-2b22f36d37d8)

**Comment by dimasciput** [comment]
@helendallas for the 'b', the nearby sites should show up on the map.

![image](https://github.com/kartoza/django-bims/assets/1979569/35117369-acc7-4d4b-b69e-d11dc5a0c5c8)

**Comment by helendallas** [comment]
Yes, the nearby sites that matched the Ecosystem type of the user would should up, so if a user wants to ad a River Site, and they click on the map, the pop up warning appears and  nearby river sites are shown......

**Comment by helendallas** [comment]
@dimasciput Please review this feature request and size it before the next FBIS sprint. I think this is quite important but am not sure how long it will take to implement.

**Comment by dimasciput** [comment]
@helendallas I've sized this ticket to 3. I'm going to work on it this sprint.

**Comment by helendallas** [comment]
Link to other ticket #3826 

All working,
