### ISSUE TITLE
Align 'Edit Taxon' Form Fields with Template Fields

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#3894]
@schmikloi 

> the fields that are displayed in the “edit taxon” form have to be adapted to the fields that we have in the template

This ticket will take a long time to complete. I will size it as 20, indicating it will take three days to implement. However, I may need additional time.

**Comment by dimasciput** [comment]
> at the latest here it should be possible to enter the author who described the species

**Comment by schmikloi** [comment]
here adding the author works, yes

**Comment by dimasciput** [comment]
@helendallas @schmikloi 

Hi all,

I have a question about the "edit taxon" functionality.

<img width="170" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/0a098993-11e5-4e07-8ae5-4bc3dc552117">

In the current template, it specifies that an expert can edit the family. However, this doesn't seem logical when editing a taxon at the species rank, as species and family are not directly related.

It would make more sense to allow editing of the family only when editing the child of the family, such as at the genus level. For example:

Family A → Genus B → Species C

When you edit Species C, if you edit the family, you will also be editing the family for all species under Genus B.

**Comment by schmikloi** [comment]
Hi @dimasciput
I am not sure if I understand you correctly.
I asked for the family to be editable because of the following reasons:
1) when we get the bulk lists to import, it might happen that the family (or other fields) contain typos that we need to correct.
Not sure if there is a matching mechanism that would detect such errors?
2) it might well be that - after revisions of the taxonomy – single species or single genera might be placed under different families or that the family name is changed (some years ago all Apatania species were placed into Apataniidae, which before that was not a family on its own but a subfamily of Limnephilidae). This might not happen very often, but we should be prepared.
Does this make sense to you?

**Comment by timlinux** [comment]
So we propose to show:

Read only lineage for each taxon on the taxon editor
Parent pick list that will let you reallocate it to another e.g. genus

If you want to in toto move the members of a genus to a new family, you reallocate the genus to the new family. If you want to move only an individual species you edit the species and reallocate it to a new genus.

**Comment by schmikloi** [comment]
and there should be the option to add anew family, but this is there anyway I suppose...

**Comment by helendallas** [comment]
@schmikloi @dimasciput The functionality to add a new family is not yet included (except if the family is already on GBIF), this will need to be done. Probably best to revise this form for the case when the family is not on GBIF. 

@schmikloi Is it likely that FADA experts would want to add a family that is not on GBIF?

<img width="985" alt="Screenshot 2024-06-20 at 13 59 47" src="https://github.com/kartoza/django-bims/assets/45286876/a244c234-e8e7-4cfd-acc3-3ec3a623da1c">

**Comment by schmikloi** [comment]
@helendallas not sure, really... but I know that some taxa groups are quite a mess on GBIF, so it could well be...

**Comment by helendallas** [comment]
Closing this as sure it is death with In the upload form
