### ISSUE TITLE
Map zoom issue

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3904]
When doing data query work flows the FBIS map sometimes changes zoom level which is distracting.

Examples include:

- After hitting the refresh button the map randomly zooms in (I think it should zoom out back to the wide, default view of SA after hitting refresh?)
- When querying data using lasso tool, there is a distracting  zoom change when clicking update search
- A similar distracting zoom change occurs when doing other actions like changing data source to just FBIS, or changing the biodiversity module

**Comment by helendallas** [comment]
Comment from #3819 

At the moment when I use the map to zoom to a site, and then click on one of the detailed dashboards to view the data, and then close the dashboard, the map defaults to the full zoomed out view.

This is cumbersome because then I need to find the site again and zoom in and start again.

Please make it that the same zoom level is retained after closing a dashboard.

I am now going to close #3819

**Comment by dimasciput** [comment]
@jeremyshelton @helendallas deployed to staging site : fbis.sta.do.kartoza.com

**Comment by jeremyshelton** [comment]
Hi @dimasciput 
Thanks for addressing this. It is definitely improved but unnecessary zoom changes are still happening when I:
- [ ] Search for a species
- [ ] Hit refresh on the search bar
- [ ] Change biodiversity module

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton I have checked and it is much improved. 

I only have a change happening when I hit refresh, but in a way I expect this.  Maybe we can accept for now and reassess once FBIS is on multi-tenant.
