### ISSUE TITLE
Add option to filter taxon manager tags with OR and AND

### ISSUE THREAD

**Issue by dimasciput** [kartoza/django-bims#4001]
We need to add an option to filter tags using either OR or AND logic in our application. Currently, the filtering mechanism does not support this feature.

The ticket request was created from this comment https://github.com/kartoza/django-bims/issues/3631#issuecomment-2149818590

**Comment by dimasciput** [comment]
@schmikloi @helendallas 

<img width="609" alt="image" src="https://github.com/kartoza/django-bims/assets/1979569/eb93454b-5654-4876-9c37-6afdb18a8555">

You can now filter tags using OR or AND.

**Comment by schmikloi** [comment]
hi @dimasciput 
thanks! works properly!

**Comment by helendallas** [comment]
@dimasciput @schmikloi I ran this but not working for me?

Original request was:
if I filter for two tags, they are combined with an OR (so I get all freshwater and all limno-terrestrial); can we implment an option that we combine the tags with an AND, so that I get only those which have both tags?

I did this filter
<img width="594" alt="Screenshot 2024-06-20 at 09 57 31" src="https://github.com/kartoza/django-bims/assets/45286876/2eeeaaba-1326-490f-a129-c07d4342da64">


But got all freshwater and tag 2 returned. Not only the taxa that had both tags.


<img width="1199" alt="Screenshot 2024-06-20 at 09 57 46" src="https://github.com/kartoza/django-bims/assets/45286876/63a2c63d-faf3-42ac-a1c0-00116ed6fae5">

**Comment by dimasciput** [comment]
@helendallas could you hard refresh first?

**Comment by schmikloi** [comment]
hmm that is my result for OR
<img width="1382" alt="Bildschirmfoto 2024-06-20 um 10 41 34" src="https://github.com/kartoza/django-bims/assets/123731080/f2829b9f-8180-4f30-9882-eacad872686b">


and for AND
<img width="1394" alt="Bildschirmfoto 2024-06-20 um 10 41 49" src="https://github.com/kartoza/django-bims/assets/123731080/f9aa9aa2-bdf6-4333-a9a2-f20c91effa6e">

**Comment by helendallas** [comment]
Weird. I did a hard refresh. and same result. I also tried @schmikloi test, and got all. I am on safari - not sure if that has anything to do with it?

**Comment by dimasciput** [comment]
@helendallas did you click apply when you change the OR to AND?

**Comment by helendallas** [comment]
yes, I clicked Apply

**Comment by dimasciput** [comment]
@helendallas, you can go to the admin page to edit the tags at [this link](https://fada.sta.do.kartoza.com/admin/taggit/tag/).

Tags are not at a global level, so different tenants can have different tags. However, in the future, when species are fetched from other tenants, their tags will also be imported.

**Comment by dimasciput** [comment]
It seems the 'fresh water' tag is added by Tim https://fada.sta.do.kartoza.com/admin/taggit/tag/65/change/.

**Comment by helendallas** [comment]
Thanks @dimasciput Curious where all the existing tags come from?

**Comment by schmikloi** [comment]
@helendallas Tim added "fresh water" when he was showing the recent developments to us, I added "freshwater" and "limbo-terrestic" as these terms are used for FADA

**Comment by helendallas** [comment]
Closing ticket now as working for me as well.

**Comment by schmikloi** [comment]
Dear sender,

I am attending various conferences and also will be on vacation. I will be able to respond reliably only after August 11th. In urgent cases, please feel free to send me a reminder. Thanks for your understanding! 

Have a great summer!
Astrid
