### ISSUE TITLE
upload test

### ISSUE THREAD

**Issue by schmikloi** [kartoza/django-bims#4316]

**Comment by schmikloi** [comment]
Hi @dimasciput,

I did an upload test again so that I can tell Géraldine which columns need to be changed or added before we can actually upload data; 
Now I want to report the following issues:

- I added the yellow marked columns in the beginning of the file as otherwise the upload would not have been possible
- upload took very long for the 13 species I tested (6 minutes); I did it more than once and the last one (Version 4 was very quick)
- I got an error and an success file at the first try, but the second version worked well
- I have marked the fields in the attached file in orange that were not imported

- @parasitic: we have a host column; I do not expect that we will have many entries here, but could we add it to the "Additional information"

- @common name: 
    - we also have vernacular names in our template where we indicate the language in a separate column; should we summarize this into one field like "Wassergeistchen (German); Waterghost (English)"? 
    - in the additional information view the Common name line is empty; if I go into the edit mode then I can see my entries, but the content seems to be cut off
 
- @conservation status: whatever I enter in the column, it ends up as "not evaluated"

- @GBIF key: this is generelly not imported, neither as link in one of the yellow columns nor as value from the last column;
additionally: I have deleted the old Ostracoda list and imported the new one; still Alicenula serricaudata is the only species that shows a GBIF link though I did not have a GBIF link or key  in the upload file 


Could I please suggest a slight change of field order in the editing mode, so that similar fields appear after each other; after Status:
- Taxonomic Comments
- Taxonomic References
- Common name (needs a capital n)
- GBIF Key
- Biographic distribution (needs a capital d and no s in the end; and has to be Bio**geo**graphic --> Biogeographic Distribution)
- Biogeographic Comments
- Biogeographic References
- Tags
- Environmental Comments
- Environmental References
- Conservation Status
- Conservation Comments
- Conservation References

- @Taxon name in this list: it is not editable and currently only shows only the species-part of the taxon name; is this intended?


Let me know if something is not clear.
THANKS!

[Ostracoda_upload_full_completed_v4.xlsx](https://github.com/user-attachments/files/17412608/Ostracoda_upload_full_completed_v4.xlsx)

**Comment by dimasciput** [comment]
@schmikloi @helendallas I have updated the uploader. Please test it again. Here are some of the issues that have been resolved:

> upload took very long for the 13 species I tested (6 minutes); I did it more than once and the last one (Version 4 was very quick)


This should be fixed in production

___

> parasitic: we have a host column; I do not expect that we will have many entries here, but could we add it to the "Additional information"

The data will be automatically added to the system.

___

> common name:
> 
> we also have vernacular names in our template where we indicate the language in a separate column; should we summarize this into one field like "Wassergeistchen (German); Waterghost (English)"?
> in the additional information view the Common name line is empty; if I go into the edit mode then I can see my entries, but the content seems to be cut off

Yes you can now use that format, but please use three code language https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes. 
So it should be "Wassergeistchen(ger);Waterghost (eng)"

___

> conservation status: whatever I enter in the column, it ends up as "not evaluated"

Please avoid using abbreviations. If referring to 'LC,' it should be written as 'Least Concern.' You can find the full list of categories here: https://en.wikipedia.org/wiki/IUCN_Red_List#Categories"

___

> Could I please suggest a slight change of field order in the editing mode,

This has been updated

**Comment by dimasciput** [comment]
@schmikloi 

> 2. you said that the data will be automatically added to the system; but I wonder where I find them then...

all the data will be stored in the database, and you can see it from admin page 

![image](https://github.com/user-attachments/assets/867a5b58-b9f0-4821-b69c-ed21b232fbc4)

It seems like you're making "parasitic" a tag? Since the value is 'y', it automatically becomes a tag.

> 3. the following columns are not imported (or not visible?): subfamily, tribe, subtribe, subgenus, species group, subspecies, hosts, GBIF key (see also my comment above)

You need to upload the subgenus taxa first, either through the uploader or the form. The system will then automatically use it as the subgenus. @helendallas , could you help me with this? 

Also, please update your CSV with this field. I think I used your old format, so please use this one. I can update my code as well, but it will take some time.

Subspecies → SubSpecies
Subphylum → SubPhylum
Subfamily → SubFamily
Subtribe → Sub Tribe
Subgenus → Sub Genus

> for the vernacular name, I had two in my test file, but only the English one was imported; all German one were lost

They are stored in the database, I have checked. However, we currently only display English vernacular names. Do you want to show all the names? It might look cluttered, and sometimes the common names are fetched from GBIF.
cc @helendallas

**Comment by schmikloi** [comment]
> 
> > 3. the following columns are not imported (or not visible?): subfamily, tribe, subtribe, subgenus, species group, subspecies, hosts, GBIF key (see also my comment above)
> 
> You need to upload the subgenus taxa first, either through the uploader or the form. The system will then automatically use it as the subgenus. [@helendallas](https://github.com/helendallas) , could you help me with this?
> 
> Also, please update your CSV with this field. I think I used your old format, so please use this one. I can update my code as well, but it will take some time.
> 
> Subspecies → SubSpecies Subphylum → SubPhylum Subfamily → SubFamily Subtribe → Sub Tribe Subgenus → Sub Genus
> 

@dimasciput 
I tried to upload the file with changed headers, but I get an server error 500.

And: how can I delete entire species groups (like my Ostracoda3 (they were only for testing)

**Comment by schmikloi** [comment]
> > 5\. the following columns are not imported (or not visible?): subfamily, tribe, subtribe, subgenus, species group, subspecies, hosts, GBIF key (see also my comment above)
> 
Can you please let me know how we can handle the GBIF key so that it gets uploaded? Thanks!

**Comment by helendallas** [comment]
For all other BIMS we have tried to limit vernacular names to English as it can getting really really messy. The person can easily jump to GBIF for the full range of names. If Astrid wants this then please only make it for FADA, not all the BIMS.

**Comment by schmikloi** [comment]
I am not sure how many vernacular names are there on GBIF for freshwater species...?
And I am not sure how many of these vernacular names we will get; so we can leave it with the English names for now, but maybe add the others later; as they are stored in the database, this should not be much of an issue, correct?

**Comment by schmikloi** [comment]
> Also, please update your CSV with this field. I think I used your old format, so please use this one. I can update my code as well, but it will take some time.
> 
> Subspecies → SubSpecies Subphylum → SubPhylum Subfamily → SubFamily Subtribe → Sub Tribe Subgenus → Sub Genus

I changed the headers in the upload file but the content is still not uploaded...

**Comment by helendallas** [comment]
Closing by way of #4377
