### ISSUE TITLE
Filter paper trail

### ISSUE THREAD

**Issue by toniolsen** [kartoza/django-bims#533]
A filter paper trail should be shown somewhere on the detailed dashboard (E.g. searched by conservation status and Ecoregion). This applies to both species and site search.

**Comment by timlinux** [comment]
We are talking about breadcrumbs here so that we can see all the applied filters that are active. We also need a more visual way to know when a filter is active versus when no filters are applied.

**Comment by timlinux** [comment]
I think there are a few things we should be doing here:

* Change the drawer text colour to green when a filter in that drawer is active

<img width="635" alt="screenshot 2018-12-04 at 09 12 51" src="https://user-images.githubusercontent.com/178003/49424980-edbbb880-f7a4-11e8-8312-ed6f244cc95c.png">


* We should change the backgound of the search icon and bar to e.g. darker yellow (@carina1000 to share colour code) when a search is active so that you can see it is active even if search is hidden.

<img width="510" alt="screenshot 2018-12-04 at 09 15 58" src="https://user-images.githubusercontent.com/178003/49425081-3ffcd980-f7a5-11e8-9928-77318d4612b8.png">


<img width="639" alt="screenshot 2018-12-04 at 09 14 49" src="https://user-images.githubusercontent.com/178003/49425041-1e9bed80-f7a5-11e8-84c7-895f5c52ec4a.png”>

* A multi-site dashboard that shows summary accross many sites, lists them as a table and lets you drill into any site.

**Comment by dimasciput** [comment]
implemented
