### ISSUE TITLE
csv download files: list of columns to include

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#777]
[Fish and SASS csv_Feb 2019.xlsx](https://github.com/kartoza/django-bims/files/2836702/Fish.and.SASS.csv_Feb.2019.xlsx)
@timlinux @dimasciput @toniolsen @Christiaanvdm 

Kartoza to use geospatial layers to inform columns for inclusion in .csv downloads. Important columns already identified for fish and SASS csvs shown in attached. We will give the same for algae and invert taxa for FBIS v3

**Comment by timlinux** [comment]
@toniolsen to review existing CSV outputs and indicate which ones need tweaking

**Comment by toniolsen** [comment]
@dimasciput @timlinux @jeremyshelton @helendallas 
The downloaded CSV columns for the fish are perfect and have all the columns necessary specified in the above csv.

I have tried to download the CSV. for many SASS sites, but it keeps giving me "processing", so I can't check if the downloaded columns are right. Maybe a bug?
![Screenshot 2019-08-05 at 10 34 19](https://user-images.githubusercontent.com/43198125/62454850-fbc73c00-b76c-11e9-97e2-b8672e8ae851.png)

**Comment by dimasciput** [comment]
@toniolsen thanks, yes that's a bug. I fixed it on the testing site, can you check it again?

**Comment by toniolsen** [comment]
Okay @dimasciput it's working on the testing site.
All the columns for SASS are there, but I noticed the details under the headings aren't correct. For example Longitude = Lower Foothill. See attached spreadsheet. There is a mix match of details and headings. 

[db11fad128c3ac7f37dc9d0a39b3aa8d.xlsx](https://github.com/kartoza/django-bims/files/3467294/db11fad128c3ac7f37dc9d0a39b3aa8d.xlsx)

**Comment by dimasciput** [comment]
@tonyolsen can you copy here the link of the SASS page which has an issue?

**Comment by toniolsen** [comment]
http://testing.healthyrivers.kartoza.com/sass/dashboard/10206/?taxon=&search=A2CROC-HARTB&siteId=10206&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=[%22validated%22]&sourceCollection=&ecologicalCategory=

**Comment by dimasciput** [comment]
@toniolsen 
it looks fine to me : 
[d8d0ff70cd2c507999d469c08fbf8159.csv.zip](https://github.com/kartoza/django-bims/files/3470118/d8d0ff70cd2c507999d469c08fbf8159.csv.zip)

maybe try to open the file with other csv reader app?

**Comment by helendallas** [comment]
@dimasciput @toniolsen 
I checked - it is also fine for me. attached.

I did note some slight edits needed, and more info re filter ..
[SASS Csv_Comments Helen.xlsx](https://github.com/kartoza/django-bims/files/3470774/SASS.Csv_Comments.Helen.xlsx)
..please see excel file

**Comment by jeremyshelton** [comment]
@helendallas please check you are happy with the SASS .csv edits requested?

**Comment by helendallas** [comment]
@dimasciput 
For **CSV of SASS Summary data** the following needs attention: this is the same for single and multiple sites

- Filter history - This should be columns of the actual fields such as Ecoregion, Political Region etc  - whatever was selected by the user. At the moment this is what is shown:
{u'search': u'JONKERSHOEKRIVIER', u'sourceCollection': [u'fbis'], u'conservationStatus': []}

- Reference Category - no data returned.
- Study Reference - no data returned

For **CSV of SASS Taxa per biotope** the following needs attention: this is the same for single and multiple sites

- Filter history - This should be columns of the actual fields such as Ecoregion, Political Region etc  - whatever was selected by the user. At the moment this is what is shown:
{u'search': u'JONKERSHOEKRIVIER', u'sourceCollection': [u'fbis'], u'conservationStatus': []}

FBIS Site Code  -not in capitals
Refined Geomorphological Zone  - still written as Geomorphological   zone ground truthed
Collector or owner - shown as Helen_Dallas instead of Helen Dallas
- Reference Category - missing
- Study Reference - missing
