### ISSUE TITLE
Sites layer takes long to load

### ISSUE THREAD

**Issue by timlinux** [kartoza/django-bims#995]
@NyakudyaA can we cache the sites layer or something to make it load quicker for the initial default page view (before any filters etc. are applied).

@dimasciput can you put. a progress indicator in place if possible while loading the page so the user knows the sites layer is on its way?

**Comment by NyakudyaA** [comment]
@dimasciput I have published a new layer in GeoServer. Please note the layer is a materialized view.
* It's better than the normal view you had in the DB.
* It has triggers to refresh the underlying data once it gets updated.
* It also filters the sites to show points that are within the boundary of South Africa. 
* I also published the layer as a normal table rather than a SQL view in GeoServer

The original layer you had is still available just in case you need to use it.

@timlinux I avoided having to cache the layer so that if new sites are loaded in the database we would have to clear the cache and reseed again

**Comment by dimasciput** [comment]
> It also filters the sites to show points that are within the boundary of South Africa.

We shouldn't do this, it just hides the layer but the data is still there, and we could still search it. We need to filter it from the site.

**Comment by dimasciput** [comment]
> I also published the layer as a normal table rather than a SQL view in GeoServer

This doesn't work with our current search implementation, because I need the Geoserver to access the sql view that generated from the search results.

**Comment by NyakudyaA** [comment]
> > I also published the layer as a normal table rather than a SQL view in GeoServer
> 
> This doesn't work with our current search implementation, because I need the Geoserver to access the sql view that generated from the search results.

I will publish it as a SQL view

**Comment by NyakudyaA** [comment]
> > It also filters the sites to show points that are within the boundary of South Africa.
> 
> We shouldn't do this, it just hides the layer but the data is still there, and we could still search it. We need to filter it from the site.

Ok. But are the searches based on the view. If so the data should not be searchable because the point's outside South Africa will not be in the view itself

**Comment by dimasciput** [comment]
> Ok. But are the searches based on the view. If so the data should not be searchable because the point's outside South Africa will not be in the view itself

No, the search creates a sqlview not based on the sql view.

**Comment by dimasciput** [comment]
descoped - after discussion with Tim
